runbox/runbox7

src/app/canvastable/canvastable.ts

Wheel deltay was divided by 100. Remove divide by 100 so that it scrolls one row per wheel tick.

canvastable: increase mousewheel scroll speed

---

src/app/xapian/searchservice.ts

For new users no search index is yet generated on the servers. However the user may still generate an index in locally in the browser, and will be prompted about that when viewing the app for the first time. After accepting a local index, the app will look for an index on the server to start from - which is good if it's an account with many messages. For new accounts there will only be one or two messages and no search index exist on the server, and a new prompt shows about this. This pull request will remove that second prompt, and just create the local index immediately (since the user already accepted this in the first prompt).

local index: skip alert about no server side index

---

backend-proxy-remote.conf.js

We originally had the `secure` option set to false for the webpack dev server proxy in order to allow backend servers without a valid SSL certificate (which we had on our devrig). Now with developers using the prod servers as backend for frontend development we should require a valid certificate for the backend, and additional devrig servers should have a valid SSL cert.

dev-setup: require valid SSL certificate for backend

---

src/app/mailviewer/singlemailviewer.component.html

Handle missing `to` header field in email. Mailviewer didn't handle this.

mailviewer: handle missing to-header

---

src/app/canvastable/canvastable.ts

Take into account pixels, lines or pages mode. With a mousewheel firefox uses lines mode, while chrome uses pixels mode. This PR checks the delta mode and adjusts the scrollspeed there after.

canvastable: Adjust scroll speed according to delta mode

---

README.md
backend-proxy-remote.conf.js

When using a custom backend for developing instead of production at runbox.com, the backend host url has been passed as a last argument to `npm start`. Angular CLI complains about an unknown option - so instead use an environment variable for the backend host configuration.
Starting dev. env with a custom backend can then be done like this:
`RUNBOX7_ANGULAR_BACKEND_HOST=https://yourvmhostname npm start`
Readme file is updated with info about this.

dev-env: use environment variable for backend proxy host

---

src/app/mailviewer/singlemailviewer.component.html
src/app/mailviewer/singlemailviewer.component.ts

For HTML mails print output showed only headers (issue #25). Fixed so that HTML content is included in print.

mailviewer: Include HTML mail content in print

---

README.md

The current displayed README.md does not render the =npm install=
properly. This patch fixes the format to use backticks.

doc(README): Fix format.

---

src/app/compose/compose.component.ts
src/app/compose/emailvalidator.spec.ts
src/app/compose/emailvalidator.ts
src/app/compose/mailrecipientinput.component.html
src/app/compose/mailrecipientinput.component.ts
src/app/rmmapi/rmmhttpinterceptor.service.ts

- Filter invalid addresses from search index suggestions
- Fixed missing validation of manually written email addresses in the recipient fields
- Show REST server validation errors and inform draft not saved

compose: validation of recipients #39

---

e2e/login/login.e2e-spec.ts
e2e/login/login.po.ts
e2e/mockserver/mockserver.ts
src/app/rmmapi/rmmhttpinterceptor.service.ts

Users experienced 2FA challenge not showing after started using http interceptor also for login network traffic (to get progress bar showing while logging in). This ensures that the 2fa challenge does not throw an error.
Also added e2e test for 2fa challenge

fix: 2FA challenge not showing because of error thrown by http interceptor

---

src/app/app.component.ts

Implemented workaround for xapian query listing `Inbox OR INBOX` as suggested in issue #69

folderlist: #69 handle messages stored in uppercase named INBOX

---

src/app/app.component.ts
src/app/mailviewer/rmm7messageactions.ts
src/app/mailviewer/singlemailviewer.component.html

This fixes that the snackbar popping up after reporting "not spam" is not dismissed.

bugfix: reporting not spam snackbar was not dismissed #86

---

src/app/app.component.ts
src/app/directives/horizresizer.directive.ts
src/app/mailviewer/singlemailviewer.component.ts

Also fix for mailviewer vertical position/height being 64 pixels below the table causing an empty space when the header toolbar is visible.

Remember mailviewer orientation (#84)

---

e2e/compose/compose.e2e-spec.ts
e2e/compose/compose.po.ts
e2e/folders/emptytrash.po.ts
package.json
src/app/app.component.ts
src/app/compose/compose.component.ts
src/app/updatealert/updatealert.service.ts

- In compose: Fix and E2E-test for `To` input field to be in focus when creating a new empty draft, but if there's text in the body focus on that field. E2E test verifies this.
- In development drop using the `--aot` option for `npm start` as it is faster for rebuilding cycles.
- Disable service worker interaction (notifications, update checks) in dev environment as it creates error messages in the console we don't need to see.
- end-to-end tests (e2e): Fix for flapping "empty trash" test which seems to be caused by an "overlay" when opening the popup menu for the trash folder.

Compose initial input focus

---

src/app/contacts-app/contact-details/contact-details.component.html
src/app/contacts-app/contact.ts
src/app/contacts-app/contacts-app.component.html

Previously we mostly used full names everywhere, which caused problems
when a contact only had a nickname, without a real name. This attempts
to show all possible information, ensuring that nothing is left out.
This addresses a user request: https://community.runbox.com/t/announcement-runbox-7-contacts-contact-sync/794/5

Contacts: improve the way contact names are displayed

---

src/app/contacts-app/contacts-app.component.ts

Contact sort would previously mishandle contacts with empty first/last names. This makes sure they always get treated as "last".

Contacts: fix contact sorting for contacts with empty names

---

backend-proxy-mock.conf.js
e2e/compose/compose.e2e-spec.ts
e2e/compose/compose.po.ts
e2e/mockserver/emailresponse.ts
e2e/mockserver/mockserver.ts
src/app/compose/compose.component.ts

Simple fix for html message not included which was caused by the html editor not initialized. Needed a timeout to wait for the editor element to be available.
Most work here is about the e2e test that will display a list of messages in the inbox. Click on one of them. View it as HTML. Click the reply button, and finally inspect that the html editor is opened and contains the text from the replied email.

Compose forward html fix #95

---

src/app/mailviewer/singlemailviewer.component.ts

to prevent reverse tabnabbing as described in issue #116

fix(mailviewer): #116 added rel="noopener" on links

---

check-prod-bundle-dependencies.js
e2e/compose/compose.e2e-spec.ts
package.json
src/app/folder/folderlist.component.ts

add script to check that installed packages in node_modules matches versions in package-lock.json
the script will complain if the version hashes in node_modules are not the same as in package-lock.json
Also added a fix for empty trash/spam so that instead of used cached folder lists on the client, get the list from the server and run delete operations on the message lists from that.

feat(bundling): check package versions before build + fix(empty-trash/spam): get list from server

---

src/app/xapian/messageinfo.spec.ts
src/app/xapian/messageinfo.ts

- handle empty subject when clicking reply
- add unit test expectation for empty/null subject
fixes #146

mailviewer(fix): reply when empty subject (issue #146)

---

src/app/canvastable/canvastable.ts
src/styles.scss

This enables touch zoom also on the canvastable. Currently it is not possible to revert zoom if accidentally zoomed in on the table, so enabling zoom solves that.
The alternative is to try disable zoom entirely, but in some cases you may want to be able to zoom in on content.
Also added a fix for #152 by setting font-size on `mat-form-field` to 16px. (iOS requires min 16px font size no input fields, otherwise automatic zoom will occur).

canvastable(feat): enable touch zoom

---

e2e/canvastable/canvastable.e2e-spec.ts
e2e/canvastable/canvastable.po.ts
e2e/dialog/synchronizeprompthandler.ts
src/app/canvastable/canvastable.ts

Fixing an annoyance when selecting multiple rows, that the first clicked row was not selected. Also handling that rows in between were not selected if moving mouse fast. Now also possible to undo selection by dragging back up again.
Added end to end test too.

Canvastable drag select

---

e2e/canvastable/canvastable.e2e-spec.ts
e2e/canvastable/canvastable.po.ts
src/app/canvastable/canvastable.ts

* prevent selecting row from dragstart event when drag-selecting in checkbox column
* add e2e test for selecting one row
* **fixes flapping e2e test for selecting multiple rows**

canvastable(fix): multiselect / drag conflict

---

src/app/calendar-app/event-editor-dialog.component.html
src/app/calendar-app/runbox-calendar-event.ts

I elected to keep those in a sub-struct of event, given how there's likely going to be quite a few more of those fields, and as the work on recurring events has shown so far, they're often better off detached from the CalendarEvent interface anyway.

Calendar: add the ability to view/edit event locations and descriptions

---

src/app/calendar-app/event-editor-dialog.component.ts
src/app/calendar-app/runbox-calendar-event.ts

This fixes GH#154 and makes us behave the same as other caldav clients
(iow: correctly :))

fix(Calendar): make event end non-inclusive on the backend

---

src/app/app.component.ts
src/app/canvastable/canvastable.ts

preloading messages while scrolling delays the messages we want to see when done scrolling, so only preload messages when scrolling is finished.
This will also reduce the amount of requests to the server, as we skip preloading messages while scrolling over a long list.

fix(messagetable): no preloading while scrolling

---

src/app/mailviewer/mailparser.ts
src/app/mailviewer/singlemailviewer.component.html
src/app/mailviewer/singlemailviewer.component.ts

This PR adds experimental support for decrypting messages attached as a file named `encrypted.asc`.
The encrypted attachment is forwarded to pgpapp.no where you can upload 
- add button for decrypting 'encrypted.asc' attachments
- send encrypted message to pgpapp.no and receive decrypted message
- close pgpapp.no once authorized / rejected
- parse decrypted message
- replace subject and body text with parsed decrypted content
Click the unlock button to decrypt the message
Encrypted message is forwarded to pgpapp.no where you can point to your private key (it is not uploaded or stored anywhere at the moment), and also type your passphrase and finally approve the request to decrypt.

feat(mailviewer): experimental PGP decrypt

---

src/app/calendar-app/calendar-app.component.spec.ts
src/app/calendar-app/calendar-app.component.ts
src/app/calendar-app/calendar-app.module.ts
src/app/calendar-app/calendar.service.ts
src/app/calendar-app/event-editor-dialog.component.ts

This will enable calendar interactions from the rest of the app, including adding events from email attachments.

refactor(Calendar): split a calendar service from a calendar component

---

ngmakelib-conf.js
package-lock.json
package.json

For building the library https://www.npmjs.com/package/runbox7lib which is used by the https://github.com/runbox/runbox-searchindex project as well as for the server side indexer. The library contains reusable code for indexing, which is JS-wrappers for the webassembly library and also tools for working with the email data.
Added dependency for [ngmakelib](https://github.com/fintechneo/ngmakelib) which is a tool for generating libraries from/for Angular projects. This was already in use, but missing from package.json.

fix(runbox7lib): dependencies for creating library

---

src/app/contacts-app/contact-details/contact-details.component.ts
src/app/contacts-app/contacts.service.ts
src/app/mailviewer/contactcard.component.ts
src/app/mailviewer/mailviewer.module.ts
src/app/mailviewer/singlemailviewer.component.html
src/app/mailviewer/singlemailviewer.component.spec.ts

Froms, Tos, CCs etc are now clickable, enabling the user to show the
contacts they're related to (if they exist) or add new ones.
Fixes GH-45.
Looks like this – dotted line for new contacts, solid for existing ones.

feat(mailviewer): Make email addresses clickable

---

src/app/calendar-app/calendar-app.component.spec.ts
src/app/calendar-app/calendar-app.component.ts
src/app/mailviewer/singlemailviewer.component.ts

This replaces the default attachment action for text/calendar attachments (they still have a download button, the small one).

feat(mailviewer): Import text/calendar files to Calendar

---

src/app/xapian/searchservice.spec.ts
src/app/xapian/searchservice.ts

- look for latest changed or message date in results and use as basis for new since time parameter when polling for updates
- catch failures polling/updating (e.g. being offline)

fix(localindex): update polling

---

src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/login/loginlogout.module.ts
src/app/login/logout.service.ts
src/app/menu/headertoolbar.component.html
src/app/menu/headertoolbar.component.ts

When logging out from PWA on iOS a new window is opened with the runbox.com frontpage. This fix goes to the `/LOGOUT` endpoint via an iframe instead so that no new window is opened. When LOGOUT iframe is loaded, the app is restarted so that now it's possible to restart the app on iOS ( by logging out and in again) without having to reinstall the app.
- log out via iframe so that PWA does not open a separate window (iOS)
- restart app on logout

fix: logout from PWA

---

src/app/rmmapi/rbwebmail.ts
src/app/xapian/searchservice.spec.ts

If being logged out e.g. by session timeout or another tab, Safari caches the following forbidden responses, even if logging back in again.
- add unique query parameter with timestamp when polling server for changes to avoid cache
- add todo note about replacing with REST api as REST api responses does not seem to be cached like this one (maybe because the old RMM api returns a login html page when logged out and not a prober JSON error response).

fix: avoid cache in Safari / iOS

---

src/app/calendar-app/calendar-app.component.spec.ts
src/app/xapian/searchservice.spec.ts
src/app/xapian/searchservice.ts

Separate indexing of message headers and body text contents to speed up
updating of the message list.
Also a small fix to the calendar unit test that failed to run today ( 1st of the month ) @tadzik 
issue #225

Speed up syncing of message list by separating indexing of headers and body text

---

src/app/compose/compose.component.ts
src/app/compose/draftdesk.service.ts
src/app/rmmapi/rbwebmail.spec.ts
src/app/rmmapi/rbwebmail.ts

Found that the `fullpage` plugin of tinymce caused the HTML and text preview to be wrapped with `<!DOCTYPE html><html>` etc. Removed the plugin so that this is fixed.
Also found that editor content was lost in cases where exiting compose before autosave completed. Should be fixed.
Fixed so that compose previews are updated with the correct content after editing draft.
Added test for getting message contents from rmm, and the local cache for this.

Tinymce / compose preview fixes

---

.travis.yml
package-lock.json
package.json
policy-tests/check-commit-log.js
protractor-ci.conf.js
src/app/app.component.ts
src/app/app.module.ts
src/app/canvastable/canvastable.ts
src/app/rmmapi/rbwebmail.ts
src/app/xapian/messageinfo.ts
src/app/xapian/searchservice.spec.ts
src/app/xapian/searchservice.ts

This PR adds comparing folder counts received from the server (which is displayed in the left side menu), with the actual count per folder in the local search index. If there are discrepancies, the current folder in view will be retrieved from the server, and added to the index. If the next compare still show discrepancies, a dialog will pop up and suggest downloading a fresh index from the server.
A cause of discrepancies is that the folder count from the server includes messages marked for deletion ( as mentioned in https://github.com/runbox/runbox7/issues/190 ). To prevent this we should decide on either supporting strikethrough of messages marked from deletion in Runbox7, or remove them from the counters as suggested in the issue.

Sync index on foldercount mismatch

---

src/app/calendar-app/calendar-app.component.html
src/app/calendar-app/calendar-app.component.spec.ts
src/app/calendar-app/calendar-app.module.ts

Looks like this now, instead of the previous "hidden" features :)

style(calendar): make the UI more obvious WRT calendar visibility and editing

---

src/app/canvastable/canvastable.spec.ts
src/app/canvastable/canvastable.ts
src/app/folder/folder.module.ts
src/app/folder/folderlist.component.css
src/app/folder/folderlist.component.html
src/app/folder/folderlist.component.spec.ts
src/app/folder/folderlist.component.ts
src/app/rmmapi/rbwebmail.ts
src/app/xapian/xapianwebloader.ts

**NOTE:** While the UI updates here supports reordering of the folders, the backend does not. Changing the order of folders will be immediately reflected in the user interface, but will be reset when a new folderlist is read from the server. We need backend support for setting the order of folders.
- add drag and drop reordering of folders
- fix canvas table broken drag messages to folder (was broken in 7dc8150e)
- indicate drop above / below / inside when dragging over
- move above / below / into folder ( **IMPORTANT: Backend currently only supports moving into folders, not above/below)**
- add unit test for various cases of rearranging folders
- add unit test for canvastable draggable overlay being activated on hover
- changed to using dragend event instead of dragleave
- load xapian …

feat(folderlist): drag and drop reordering

---

e2e/mockserver/mockserver.ts
src/app/folder/folderlist.component.spec.ts
src/app/folder/folderlist.component.ts
src/app/rmmapi/rbwebmail.spec.ts
src/app/rmmapi/rbwebmail.ts
src/app/xapian/searchservice.spec.ts
src/app/xapian/searchservice.ts

- remove references to rmm6 folderlist (/ajax?getfoldercount)
- add fetching folderlist from /rest/v1/email_folder/list
- add functionality for flattening the nested folderlist structure
- so that it returns same folderlist array as previously
- use priority field to sort folderlist in the frontend
- add tests for new REST endpoint and priority field
- disable folder count discrepancy check popup dialog
fixes #265

feat(rmmapi): use folderlist from REST

---

src/app/calendar-app/calendar-app.component.spec.ts

Tests expected only events from the current month to be shown.
Unfortunately, the calendar also shows all the days from next month
until the nearest sunday.
Moving the event two weeks into the future makes sure that it's never
displayed by accident. Hopefully. See you all again when the tests start
failing next month ;)

fix(calendar-app): make unit tests less time-dependent

---

src/app/folder/folderlist.component.spec.ts
src/app/folder/folderlist.component.ts

With the new priority sorting (done by getFolderCount() in RunboxWebmailAPI)
there is a risk that subfolders appear before parent folders in the
resulting list. The flattening algorithm in FolderListComponent doesn't
handle that correctly, breaks and displays nothing. This fixes it and
adds a testcase.
It feels like now that the folders are pre sorted the BFS loop (or what
looks like one :)) below could be somewhat simplified too – but that's
a task for another time.

fix(folder): make sure folders are handled correctly regadless of order

---

src/app/app.component.ts

The new, recommended ones aren't supported on Safari
which breaks the app completely.

fix(app): re-add deprecated mobileQuery APIs

---

src/app/compose/draftdesk.component.html

It now looks less like a rendering error when no drafts are available :)

style(draftdesk): Add a message to an empty draftdesk

---

src/app/app.component.ts
src/app/canvastable/canvastable.ts

when touching the table a focus event is currently triggered to take focus away from the search input field when scrolling the table. On iOS devices this causes lagging scroll, and the fix is as simple as just removing the call to `this.canv.focus()`.
Now this contains no replacement for taking away the focus from the input field when scrolling, so if you still want this you'll have to find another alternative for that.
Also fixed that if you drag the resizer next to the subject column causes the mailviewer to open, and removed the animationframethrottler which only seems to be used by the resizer. If a throttle mechanism is needed (seems not to be), probably better to find another alternative mechanism than requesting animation frames

Canvastable scroll lagging and column resize fixes

---

src/app/folder/folderlist.component.spec.ts
src/app/folder/folderlist.component.ts
src/app/rmmapi/rbwebmail.spec.ts
src/app/rmmapi/rbwebmail.ts

The previous sorting method could accidentally put child folders above
their parents, which then broke the tree rendering algorithms.
This makes sure that sorting happens at each tree layer separately,
ensuring that the structure is preserved regardless of folder
priorities.

fix(folderlist): Make sure folders appear in the right order

---

src/app/xapian/searchservice.spec.ts

This (hopefully) fixes the dreaded "FS is not defined" flapping test.

fix(tests): Ensure that xapian is loaded in each testcase

---

src/app/account-app/shopping-cart.component.ts

This could sometimes result in the API data being loaded before the
component is fully initialized, resulting in an endless loading screen,
because the HTML bindings never noticed anything new coming since the
time they were created.

fix(cart): Don't perform async queries before the component is fully initialized

---

karma.conf.js
src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/calendar-app/calendar-app.component.html
src/app/calendar-app/calendar-app.component.spec.ts
src/app/calendar-app/calendar-app.component.ts
src/app/calendar-app/event-editor-dialog.component.html
src/app/calendar-app/event-editor-dialog.component.ts
src/app/mailviewer/singlemailviewer.component.spec.ts
src/app/mailviewer/singlemailviewer.component.ts
src/app/menu/menu.module.ts
src/app/menu/sidenav-menu.component.ts
src/app/mobile-query.service.ts
src/styles.scss

This includes several refactors to the webmail to allow reusing its good ideas in other apps – this time it's gonna be the calendar :)
The sidemenu now behaves similarly to the one in the webmail: going over the content and becoming closable with the runbox logo. The month-day-view template was adjust to show less information: event details can still be read when clicking on individual days.
Notable missing bit is navigation between sub-apps in mobile view: this can now be done in app-sidenav-menu and thus shared between sub-apps.
Some screenshots:

Make calendar (more) mobile friendly

---

src/app/rmmapi/rmmauthguard.service.ts

We use to hold each navigation request until we're sure that the user is
still logged in -- effectively making the user wait until /rest/v1/me
responds, adding hundreds of miliseconds (at best!) to each route change,
and making the app appear sluggish on operations as trivial as viewing
the drafts or going to /compose.
This implements a "fast pass" for the auth checker. If we previously saw
the user being logged in, we assume they still are and immediately
direct them to where they want to be. Meanwhile, under the hood, we
check if they're actually logged in -- and if not, we kick them out to
login like we used to.
For users not previously logged in, the navigation will block like it
used to. If it does not, the redirect from login to / would result in a
dysfunctional webmail, as nothing …

refactor(authguard): Add a fast pass for previously logged in users

---

src/app/account-app/account-addons.component.html
src/app/account-app/account-addons.component.ts
src/app/account-app/account-receipt.component.ts
src/app/account-app/account-transactions.component.ts
src/app/account-app/account-upgrades.component.ts

Following the footsteps of c14aac7d, this ensures that data won't be
provided to the component before it's fully loaded: which could (and
sometimes did) result in the component code not noticing that it
arrived and showing the loading screen forever.
Also adds loading indicators to account-addons :)

fix(account-app): Use ngOnInit consistently when loading async resources

---

src/app/app.component.html

This fixes a regression introduced in e3506cb2c88d4994d71ef176d6dee6e065b412b0.
Without it the submenu is visible twice in webmail:

style(webmail): Hide nav submenu in mobile view

---

src/app/login/login.component.html
src/app/login/login.component.ts

It no longer relies on the backend to supply a valid HTML to the
frontend, and also we can now make an informed decision about where
to take the user and how.
The reason it's not using innerHTML is because that doesn't play nicely
with angular-specific HTML attributes like routerLink (as in: they don't
work at all); it's probably best to stay away from innerHTML in general
as it leads to surprising errors like this.

fix(login): Re-add the specialized expired account error

---

src/app/folder/folderlist.component.ts

folder list crashed if there were draft subfolders
This is an updated version of https://github.com/runbox/runbox7/pull/126

fix(folderlist): handle draft subfolders

---

src/app/calendar-app/calendar-app.component.html
src/app/calendar-app/calendar-app.component.ts
src/app/calendar-app/calendar-app.module.ts
src/app/calendar-app/calendar-overview.component.html
src/app/calendar-app/calendar-overview.component.ts
src/app/calendar-app/runbox-calendar-view.ts
src/styles.scss

This implements a basic (for now) calendar overview screen. I based it on tadzik/jcal to make sure it's using all the latest and greatest and to reduce the possibility of conflicts.
Currently looks somewhat like this:
Suggestions welcome :)

Calendar overview

---

src/app/app.component.ts
src/app/canvastable/canvastable.ts
src/app/canvastable/canvastablecontainer.component.html
src/app/rmmapi/messagelist.service.ts
src/app/websocketsearch/websocketsearch.service.ts
src/app/xapian/searchservice.ts

This is mostly a refactor under the hood: what used to happen here is
the column widths would be set by the providers of the columns
themselves: xapian, rmmapi, or websocket. Separation of concerns (and
basic code hygiene :)) dictates that data providers should have nothing
to do with the interface layout, so this removes that capability of
theirs -- it's now all set in the canvastable itself. An added bonus
is the fact they're now actually consistent: previously, because of the
"decentralization" of their widths, every provider would set them to
slightly different values :)
The original reason (I assume...) for having them there was that the
data providers actually know which column is which: "a 4th column"
can mean different things depending on what we're displaying. To fix
this, column …

Remember canvastable column widths

---

package-lock.json
package.json
src/polyfills.ts

By supplying a polyfill for Array.flat()

fix(folders): Make folders show up on old versions of Edge

---

src/app/canvastable/canvastablecontainer.component.html

Flex prevents the optionally displayed sorting arrow
from shifting the text downwards.
Overflow does what the overflow does :)
Takes us from this:
To this:
I tried to give it a little bit of padding on the right too, so that it doesn't cut off pixel-perfectly, but my CSS “skills” failed me :/

style(canvastable): Fix overflow and adjustment of column headers

---

src/app/account-app/stripe-payment-dialog.component.html

@gtandersen I'm not sure about the wording here: I initially included "some browser extensions might be blocking it", which can be true in some cases (I've seen overly aggresive uBlock block the Stripe domain for no good reason), but it also may less technical users feel like we're doing something dishonest and the browser is right to block it. I couldn't think of any way to be helpful while not being misleadingly scary, so I just left it like this.

feat(account-app): Offer a redirect back to rmm6 if stripe payment form fails to load

---

src/app/calendar-app/calendar-app.component.ts

It resulted in tons of PUT queries peformed on /rest/v1/calendar/ics/undefined,
wasting time, bandwidth, and making our error logs look stupid ;)

fix(calendar): Don't try to import events when user cancelled it

---

ngsw-config.json
package.json
src/app/updatealert/updatealert.component.html
src/app/updatealert/updatealert.component.ts
src/app/updatealert/updatealert.module.ts
src/app/updatealert/updatealert.service.ts
src/build/post-build.js
src/build/pre-build.js

This way we can display the upcoming version properly in the update
notes (as opposed to the old build timestamp that we used to show).
Also, knowing both the previous and the next commit hash (after this has
been deployed for a while) we'll be able to link users to changelogs
generated on the fly from a given commit range.

feat(update-notifier): Include commit hash in app update data

---

src/app/canvastable/canvastable.ts

Note: this only affects the auto-squashed view that shows up when the
canvas is being resized, and has no effect on the "Inline previews" mode
or the regular columned view.
This replaces two magic numbers with the new magic numbers which end
up working better :) Before this patch, the x of Date was dependent
on the width of the checkbox plus some padding minus the magic number
8 that made it looked good. This time the magic number is 42, which
happens to be the exact same number that was there before: it's just
more obvious now.
The x of From however used to be dependent on col.width of Date: meaning
that if in the non-wrapped view the user set the column too narrow, the
Subject would overlap the Date in the wrapped view: and since in wrapped
view the columns are not resizable, the UI …

fix(canvastable): Keep columns from overlapping in the wrapped view

---

angular.json
src/app/account-app/account-app.module.ts
src/app/app.module.ts
src/app/calendar-app/calendar-app.component.spec.ts
src/app/calendar-app/calendar-app.module.ts
src/app/contacts-app/contacts-app.module.ts
src/app/dev/dev.component.ts
src/app/dev/dev.module.ts
src/app/dkim/dkim.component.ts
src/app/dkim/dkim.module.ts
src/app/domainregister/domainregister.module.ts
src/app/profiles/profiles.component.ts
src/app/profiles/profiles.module.ts
src/tsconfig.app.json
tsconfig.json

Before this change, the build resulted in a 3.4 MB main.js bundle.
In transit (gzipped) it ended up being around 890 KB, and it took my
browser 120-130 ms to load it.
With these changes, main.js is 2.2 MB big (630 KB gzipped), and it loads
in around 100 ms -- giving us roughly a 30% smaller and 20% faster
initial page load.
Lazy loaded modules are sized as follows (uncompressed):
calendar.js:       688K
domainregister.js: 192K
contacts.js:       188K
profiles.js:       112K
dkim.js:           40K
dev.js:            20K
With calendar being understandably big (since it now includes the entire
angular-calendar package which is no longer loaded by default), the size
of remaining components is somewhat surprising(ly big). Perhaps further
improvements could be made by eliminating unnecessarily …

perf(app): lazy-load non-core modules to improve load times

---

src/app/calendar-app/event-editor-dialog.component.ts

This prevents the case when start/end date would be left empty and
accidentally set to bogus values.
Fixes GH-343.

fix(calednar): Always set default dates when creating new calendar events

---

src/app/compose/compose.component.ts

The solution isn't too pretty since the API still uses the old
ajax_send_msg under the hood. Proper error handling can be introduced
when the endpoint is ported over to the REST API.
Fixes GH-428.

fix(compose): handle ajax_send_msg errors

---

src/app/calendar-app/calendar-app.component.spec.ts
src/app/calendar-app/calendar.service.ts
src/app/calendar-app/runbox-calendar-event.spec.ts
src/app/calendar-app/runbox-calendar-event.ts

This fixes a (real) problem of non-standard timezone names in events,
as well as a theoretical problem of moment.tz timezone data actually
differing from the one we encounter in real world.
It also bumps the cache version for calendars since we now need to store
the entire jcal (not just vevent) to preserve the timezone information
in local cache.
Tests fixes required by this also mean that we're now cheating in them
much less :)
Fixes GH-478.

fix(calendar): Load timezones data from Icals instead of moment.js

---

src/app/rmmapi/rmmoffline.service.ts

Otherwise it may stay up longer than the API is offline and be a
confusing notification when everything works just fine.

fix(rmmoffline): Close the offline notification snackbar after 10 seconds

---

src/app/calendar-app/runbox-calendar-event.ts

Events under 30 minutes were pretty much invisible in day/week view.
This makes them pretend they last the whole 30 so that they're
sufficiently readable and clickable.
Fixes GH-252.

fix(calendar): Make short events appear to be longer

---

package-lock.json

This fixes all security issues reported by `npm audit`: same thing as in https://github.com/runbox/runbox7/pull/488/files, but also with seemingly irrelevant changes.

build(deps): Update some dependencies (thanks npm audit)

---

src/app/contacts-app/contacts.service.ts

They don't have their own syncTokens, so they may be included in the
result even if they syncToken itself was not updated. This is obviously
not ideal, but it's the best we can do given the limitations of the old
storage system.

fix(contacts): Make sure we pick up Runbox6 contacts when syncing

---

ngsw-config.json
src/app/changelog/changelog.component.ts
src/app/changelog/changes.ts
src/app/updatealert/updatealert.component.html
src/build/pre-build.js

We used to rely on commit hashes to determine previous releases and filter the changelog. This meant that filtering broke when the previous release was a commit not included in the changelog (for example merge commits, which usually happen before releases).
This switches us over to time-based filtering, including the timestamp epoch of the last commit in the `ngsw-config.json`, which is then compared to the timestamps kept in `changes.ts`: meaning it should work regardless of whether a particular commit is in the changelog or not.

Fix changelog `since` filtering

---

src/app/account-app/shopping-cart.component.ts
src/app/account-app/stripe-payment-dialog.component.ts

From now on we'll rely on the `tx` object alone in all payment flows,
which should finally respect the currency that may have been forced into
USD (or something else) for a particular payment because of the products
being ordered.
We're also more strict now when loading the payment products, which
should fail earlier and produce better error messages.

fix(account): Fix an edgecase where payment would not start due to currency mismatch

---

src/app/compose/compose.component.ts

Drafts were not being deleted because when saving the mid value ended
up set to a string rather than a number. This meant the delete (from
local copy) filter didnt find it.
Fixes #58

fix(draftdesk): Ensure we store Draft data correctly post save

---

src/app/compose/recipient.ts
src/app/contacts-app/contact.ts

A contact stored with no fullname / first name / last name was being
displayed as "null" <email> in the To field of compose. This amends it
to the email localpart if it would otherwise be null

fix(compose): Display email localpart for contact with no name details

---

e2e/cypress/integration/compose.ts
src/app/compose/compose.component.html
src/app/compose/compose.component.ts
src/app/compose/draftdesk.service.spec.ts
src/app/compose/draftdesk.service.ts

Logic for closing / trashing drafts is now:
If its was a new draft (not yet saved when we open it)
* If we started from "Compose", return to draftdesk (/compose)
* If we started from a "reply", return to inbox (/)
* If we started from a "email contact", return to (/contacts)
** This would be better as "the contact", need to figure out if we can do that
* Otherwise: return to drafts desk

fix(compose): Return user to origin when closing/trashing new drafts

---

src/app/compose/compose.component.html
src/app/compose/compose.component.ts
src/app/compose/emailvalidator.ts
src/app/compose/mailrecipientinput.component.ts

Prevents sending or saving draft emails when the TO field is empty or
contains invalid emails. (the latter should already be prevented by
EmailValidator). Event "change" was renamed to "updateRecipient" to
not clash with existing events and be less confusing.
Fixes #39

fix(compose): Validate TO/CC/BCC fields on save/send

---

e2e/cypress/integration/mailviewer.ts
src/app/mailviewer/singlemailviewer.component.ts

The user can set the mailviewer pane to be full height, or drag it
larger, this change is now stored in localStorage for future sessions.
Closes #518

feat(mailviewer): Store mailviewer pane height across sessions

---

e2e/cypress/integration/compose.ts
e2e/cypress/support/commands.ts

Sometimes the welcome dialog would not show up after location change,
failing the assumption in composeNew().
Tested locally this makes the test run at 100% consistency, up from the existing ~40%, so hopefully it will also make Travis runs a bit more representative :)

test(e2e): Make a flapping compose test more consistent

---

src/app/mailviewer/singlemailviewer.component.ts

Aka: Don't store the height of the horizontal pane when we're in
vertical mode, as that becomes "invisible" (33 pixels) when the pane
is actually used.
Fixes (newly reported bug)

fix(mailviewer): Ensure default horizontal pane is not invisible

---

src/app/canvastable/canvastable.ts

This makes it no longer possible to accidentally make a column so small
that it disappears completely, which sometimes happened for checkboxes.

style(mailviewer): Increase the minimal width of canvastable columns

---

src/app/mobile-query.service.ts
src/styles.scss

Now it behaves like with other mobile devices, which isn't resulting in squishing all the content together side by side.
Fixes: #441

fix(styling): Fix breakpoints for iPad Pro

---

src/app/canvastable/canvastablecontainer.component.html

The footer overlapped with message on the bottom, but wasn't visible.
Clicking on it resulted in reordering emails (just like you would click
on the corresponding header).
The footer has now 0 height, so it's not possible to click on it
anymore.
Fixes: #456

fix(canvastable): Make it possible to open email from the bottom

---

package-lock.json
package.json
src/app/calendar-app/runbox-calendar-event.ts

This eliminates our local need for a short event fix.
We can hold it off until 0.29 becomes a non-beta, but it seems to work just fine for us anyway (unless Travis is about to prove me wrong).

build(calendar): Update to the newest angular-calendar

---

src/app/mailviewer/singlemailviewer.component.css
src/app/mailviewer/singlemailviewer.component.html
src/app/mailviewer/singlemailviewer.component.ts

Now the default height of the view is 0 until the function does it's job with figuring out what height it should give to the iframe. That way there is no size jumping in between, that could confuse the user.
I was trying to do it fully in CSS but iframe wasn't cooperating enough. 
Fixes: #519

fix(mailviewer): Grow HTML view to proper size right away

---

src/app/messagetable/messagetablerow.ts

If the last time user refreshed the page was before midnight, messages they receive after midnight will now have the time shown in the table instead of today's date (that is different than the date when user refreshed the page).
Fixes: #455

fix(messagetable): Display time instead of the date for messages received after midnight

---

src/app/app.component.html
src/app/app.component.ts

"Threaded view", "Inline previews" and "Unread only" are now saved to
localstorage in the browser (and reloaded) to keep the view
consistent.
Fixes #41

fix(mailviewer): Store message list view settings in browser

---

angular.json

They're only loaded when needed anyway, and this makes debugging a lot
easier.

build(app): Enable sourcemaps for production builds

---

src/app/compose/compose.component.html
src/app/compose/compose.component.scss
src/app/compose/draftdesk.component.html
src/app/compose/draftdesk.component.scss
src/app/compose/draftdesk.component.ts
src/styles.scss

Overflow is hidden now, only 2 lines of the email are shown in the preview.
Removed blank spaces between the drafts and improved styling in general. Drafts now take up the entire width and the look throughout the page is more consistent.
Fixes: #508

fix(draftdesk): Fix text overflowing after closing draft

---

src/app/rmmapi/rbwebmail.ts

Instead of showing an error message like "folder_exists", it will show a formatted message "Folder exists"
Issue: #505

fix(errors): Better formatting of backend errors

---

src/app/app.component.ts

This fixes a bug where opening new messages
(which updates the URL fragment) would keep switching to the existing
folder and scrolling to the top of the message list each time.

fix(webmail): Make switching to the current folder a no-op

---

src/app/compose/compose.component.html
src/app/compose/compose.component.scss

As discussed with @gtandersen in [pull/649](https://github.com/runbox/runbox7/pull/649).
Edit: And little fix for desktop, because the mobile positions didn't look well on a bigger screen.

fix(compose): Push draft action buttons further apart

---

src/app/rmmapi/messagelist.service.ts
src/app/xapian/searchservice.ts

Should help with 10sec pauses/slow down when folders with large
contents exist.

fix(webmail): Only recount folder unread counts after content change

---

src/app/mailviewer/singlemailviewer.component.ts

Please review, this seems too simple! It looks like a fail in translating to a 0-based index, seems to function for me with both HTML and HTML-less emails.
Fixes #656

fix(mailviewer): Remove empty menu entry for non-HTML messages

---

src/app/compose/compose.component.scss

Background color change to the accent light blue, which makes it easier to
tell the suggestions and recipients apart.
Issue #661
[Screenshot redacted]

style(compose): Differentiate "Recently used" from recipients

---

src/app/calendar-app/calendar-app.component.html
src/app/calendar-app/calendar-app.component.scss
src/app/calendar-app/calendar-app.component.ts
src/app/contacts-app/contacts-app.component.css
src/app/contacts-app/contacts-app.component.html
src/app/contacts-app/contacts-app.component.scss
src/app/contacts-app/contacts-app.component.ts

For more consistent look throughout the app Webmail, Contacts and Calendar now have the same styling of the side pane menu.

Side-nav menu styles fix: contacts and calendar

---

src/app/app.component.html
src/app/app.component.ts

Fixes GH-647.
Looks like this:
Not super-happy about the hardcoded margin, but I don't see how else to do it nicely, save for maybe fooling it with an invisible button after it ;)

feat(webmail): Show folder count for drafts

---

src/app/app-settings.ts
src/app/app.component.html
src/app/app.component.ts
src/app/compose/compose.component.html
src/app/compose/compose.component.ts
src/app/storage.service.spec.ts
src/app/storage.service.ts
src/styles.scss

Looks like this (when opened):
We could eventually add more things to it (maybe index synchronization as well?), and also expose the same thing as a full-page settings editor, with detailed explanations and such.

Webmail settings, disabling recipients list

---

e2e/cypress/integration/folder-switching.ts
src/app/app.component.html
src/app/app.component.ts
src/app/folder/folderlist.component.spec.ts
src/app/folder/folderlist.component.ts

This includes things like going Inbox->Drafts->Inbox, /welcome->Inbox
and probably a few others. Also makes the selected section actually
hilight correctly, even if it's not a proper folder.

fix(webmail): Fix switching folders not working in some cases

---

src/app/folder/folderlist.component.html
src/app/mailviewer/singlemailviewer.component.ts
src/app/rmmapi/messagelist.service.ts

#670 
Discovered why folders don't redraw - messageCounts has content (we check that) but it doesnt know about the new folder yet. Added html to cover that possibility.
I *think* this works now, passes existing tests! Needs a chunk of manual poking (and maybe more tests designing) to see if I broke anything..

fix(webmail): Redraw folders properly after new item completed.

---

src/app/calendar-app/calendar-app.component.html
src/app/calendar-app/calendar-app.component.ts
src/app/calendar-app/calendar-app.module.ts
src/app/calendar-app/calendar.service.ts
src/app/common/background-activity-indicator.component.spec.ts
src/app/common/background-activity-indicator.component.ts
src/app/common/background-activity.service.ts
src/app/common/common.module.ts
src/app/contacts-app/contacts-app.component.html
src/app/contacts-app/contacts-app.component.ts
src/app/contacts-app/contacts.service.ts

This implements activity indicators, previously exclusive to Calendar as a generic component usable with anything within the app, with Contacts as the case study. It also introduces "multipart" activities that calendar didn't need, but contacts uses for things like deleting multiple contacts:

Activity indicators

---

src/app/compose/compose.component.ts
src/app/compose/draftdesk.service.ts
src/app/rmmapi/rbwebmail.ts

Sends the "reply_to" field for the chosen From (alias/identity) to the backend. However this seems to need a patch on the backend too, as the output isn't changed.
For #663

fix(compose): From-specific reply-to addresses saved/stored if setup

---

src/app/login/login.component.html

Closes https://github.com/runbox/runbox7/issues/705 & https://github.com/runbox/runbox7/issues/706.
I've opted to set just `inputmode` on the number inputs, rather than `type="number"` as well, as this has accessibility problems (among others). See https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/.
Although I followed [CONTRIBUTING.md](https://github.com/runbox/runbox7/blob/master/CONTRIBUTING.md), I've not updated the changelog as it appears this hasn't been done in some time, so doing so would have included a lot of unrelated entries. Let me know if I should have still updated it.

feat(login): Set inputmode to show email and numeric keyboards on mobile as appropriate

---

src/app/app.component.html
src/app/popular-recipients/popular-recipients.component.html

It now shows a hint, in a form of a button, informing the user about how to make it work:
The button is clickable and does actually synchronize the index as expected.
Fixes GH-700

feat(webmail): Always show popular recipients component if enabled, even with no local index

---

src/app/compose/compose.component.ts
src/app/compose/draftdesk.service.ts

Cursor is put at the beginning of the textarea when replying to an email.
Issue: #731

fix(compose): Set focus in textarea for replies

---

src/app/app.component.html
src/app/app.component.ts

This brings its behaviour in sync with contacts and calendar – sidepane being visible instantly (if in desktop), and still responsive.
The price we way is the animation of the sidemenu sliding in – which may be seen as nice or unnecessary, depending on your point of view (and the performance of your computer). To be discussed, @gtandersen @davidbowdley.

feat(app): Speed up the way sidemenu appears on the webmail page

---

src/app/canvastable/canvastable.ts
src/app/canvastable/canvastablecontainer.component.html
src/app/canvastable/canvastablecontainer.component.scss

Because of some typos, they weren't changing while sorting was changed, and only the "arrow up" icon was showing.
Additionally, moved the sorting icon to the right side of column name. This prevents the name from snapping to the side when the icon appears.

fix(canvastable): Make sort icons show actual sorting direction

---

src/app/account-app/account-app.module.ts
src/app/account-app/account-renewals.component.html
src/app/account-app/account-renewals.component.ts
src/app/account-app/sub-account-renewal-dialog.ts

Fixes GH-425.
Looks like this:
Hovered: 
Clicked:

feat(account): Add a way to view subaccounts associated with a product

---

src/app/sentry-error-handler.ts

Couldn't figure out an easier way to do it without breaking RunboxWebmailAPI (see the comments), so it is a bit awkward.

feat(sentry): Include user data in error reports

---

src/app/start/startdesk.component.ts

If the email we received was sent to us with some capitalized letters in the address i.e. `ABC@runbox.com`, the overview didn't know it's our address and was showing it instead of the sender's email address.

fix(start): Fix case sensitivity for address matching

---

src/app/contacts-app/contacts-app.component.ts
src/app/contacts-app/contacts.service.ts

Attempting to run all contact imports, then do the reload() rather than one per contact (which is a bit crazy for a large import)

fix(contacts): Only sync once during import of many contacts

---

src/app/start/startdesk.component.html
src/app/start/startdesk.component.scss
src/app/start/startdesk.component.ts

Extracted from https://github.com/runbox/runbox7/pull/794 and applied on top of current master.
Looks pretty bad on mobile and takes up a ton of space though:
Any ideas for improvements (@kvviecien? :))

Startdesk folder selector

---

src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/start/startdesk.component.html
src/app/start/startdesk.component.scss
src/styles.scss

Most changes extracted from #794 (except for Folder Selector which is being integrated by tadzik in #841) and applied on top of current master.
Desktop view for consistency is styled the same way as Compose.
Applied condensed layout in heading area (Geir's suggestion in #794).
<kbd><img src="https://user-images.githubusercontent.com/24294620/101672281-f7441f00-3a55-11eb-8287-963f6cf474f7.png" width="800">
</kbd>
For mobile the section title moved to the top bar to save space
<kbd>
</kbd>

Startdesk fixes

---

src/app/app.component.html

It doesn't work with no xapian index available, and it doesn't communicate that fact very well (at all).

fix(app): Hide the overview button if no local index is available

---

e2e/cypress/integration/folders.ts
src/app/app.component.ts
src/app/folder/folderlist.component.html
src/app/rmmapi/rbwebmail.ts

Fixes: #858
Also added: updates to local index so that the changes are seen faster.
Not working (how on does this work when we delete using the canvas pop up menu?) - removing items from the canvas, if we open the Trash folder, then hit the "empty trash" button on the folder

fix(mailview): Delete trash more efficiently (with less errors)

---

src/app/compose/compose.component.ts

Fixes a problem where the wrong reply to is sent to the server.
Situation 1 -- when it leaks the main identity email: in RMM7, if click "compose", then fill in the "To" field, then change the "From" field to my identity, it uses the last loaded reply_to
Situation 2 -- when it does NOT leak the main identity email: in RMM7, if click "compose", then change the "From" field to my identity, then fill in the "To" field, it uses the expected reply to

fix(compose): always ser a reply to when the "From" changes

---

angular.json

The usual (and recommended) way of just including these icons in
/assets/ didn't do anything, presumably because they're JS now, so won't
unless they're treated as part of scripts? I don't have a better idea.
Perhaps using tinymce-angular would be less of a PITA.

fix(tinymce): Make icons load again

---

src/app/account-app/account-app.component.html
src/app/account-app/account-app.component.ts
src/styles.scss

Current view of the menu:
* Mail
* Identities
* Manager
* Retrieve
* Filter
* Access
* Hosting
* Email Hosting
* Domain Hosting
* Web Hosting
* Domain Registration
* Account & Security
* Account Details
* Account Security
* Subscriptions
* Main Account Plans
* Add-ons & Sub-Accounts
* Active products & Renewals
* Transactions
* Card Details
Next step: Account Security would be it's own header called Security and would be moved to the bottom:
* Security
* Two-Factor Authentication
* Manage Services
* App passwords
* Last logins
* Sessions
<kbd><img src="https://i.imgur.com/o3wTcSU.png"></kbd>

Settings hub with menu based on existing Runbox7 items

---

backend-proxy-remote.conf.js
e2e/cypress/integration/calendar.ts
src/app/calendar-app/calendar-app.component.spec.ts
src/app/calendar-app/calendar-app.component.ts
src/app/calendar-app/calendar-app.module.ts
src/app/calendar-app/calendar.service.spec.ts
src/app/calendar-app/calendar.service.ts
src/app/calendar-app/event-editor-dialog.component.html
src/app/calendar-app/event-editor-dialog.component.ts
src/app/calendar-app/import-dialog.component.ts
src/app/calendar-app/runbox-calendar-event.spec.ts
src/app/calendar-app/runbox-calendar-event.ts
src/app/calendar-app/runbox-calendar.ts
src/app/rmmapi/rbwebmail.ts
src/styles.scss

Generate angular calendar event objects from "outside" the
RunboxCalendarEvent object (CalendarService now handles it), each RCE
object links to its main ICAL.Event object (which will be a separate
one if its an exception event).
TODO:
* Editing / saving of changes (changed nothing so far - needs to ensure we save/update recurring events, exceptions, or create new exceptions if needed?)
[x] Timezone support - set user timezone (from account settings) on new created events (and on floating/unset ones if edited) - display/edit things in user's timezone (no matter where their browser currently is)
* Simple test - 5 day event in April 2021, with one exception
[test45.txt](https://github.com/runbox/runbox7/files/5370279/test45.txt)
* Bigger test from iCloud/Dave, recurring daily/weekly/monthly …

fix(calendar): Refactor ical event handling to treat each uid as one item

---

src/app/profiles/profiles.component.html
src/app/profiles/profiles.default.html
src/app/profiles/profiles.default.scss
src/app/profiles/profiles.default.ts
src/app/profiles/profiles.lister.html
src/app/profiles/profiles.lister.scss
src/app/profiles/profiles.module.ts
src/styles.scss

Backend changes it needs: 
- ability to edit profile's "type" from stage001
- "from_priorities" changes from stage002
Adds a way to choose identity for compose. The user can choose from all the identities and aliases.
Screenshots:
<kbd><img src="https://i.imgur.com/2FVBsqq.png"></kbd>

Main Identity changes

---

src/app/profiles/profiles.component.html
src/app/profiles/profiles.editor.modal.html

* Add links to alias management (https://runbox.com/mail/account_alias)
-- On Identities page - [Screenshot](https://i.imgur.com/u0OzFz7.png)
-- In the edit dialog (only if editing an alias) - [Screenshot](https://i.imgur.com/AHnlVBL.png)
* Remove Delete button from aliases and current default identity (the one visible on the top)
* Remove alias count info
* Add warning for the user if they reached maximum number of allowed aliases - [Screenshot](https://i.imgur.com/U31jaLw.png)

Identities fixes

---

src/app/account-security/account.security.component.ts

Safari isn't inputting the current password into the password
confirmation dialog, testing to see if this helps.
Maybe fixes #802

fix(settings): Add hints for password input, and dialog modal

---

src/app/menu/headertoolbar.component.html

Settings button in header has incorrect URL. It was pointing to non-existing page.

fix(menu): Fix Settings URL

---

src/app/account-app/account-app.component.html
src/app/account-app/account-app.component.ts
src/app/account-app/account-welcome.component.html
src/app/account-app/account-welcome.component.ts

- Add "Email Aliases" under "Mail" (link to https://runbox.com/mail/account_alias)
- Add "Sub-Accounts" under "Account" - visible only to main accounts (link to https://runbox.com/mail/account_account)
- Split "Account & Security" into "Account" and "Security"
- Match icons in the side menu with the ones in the main settings screen

refactor(settings): Add missing menu items and adjust items order

---

src/app/contacts-app/contact-list.component.ts
src/app/contacts-app/contact.spec.ts
src/app/contacts-app/contact.ts
src/app/contacts-app/contacts-app.component.ts
src/app/contacts-app/contacts.service.ts

This fixes some bugs reported by @davidbowdley, starting from unnamed contacts being filtered out by search (fixed in 81d4a253270ed886d7a2696598fa5e40db471102), followed up by other things uncovered by that.
The user-facing change is that creating contacts with no deducible name is no longer disallowed – explained more in depth in the [commit](https://github.com/runbox/runbox7/commit/89d3364c072febbb1e938fa3cb5572341eb8cb07) that changed it.

Fix unnamed contacts

---

src/app/folder/folderlist.component.ts

fix(folders): Display top-level folders in user-sorted order

---

src/app/app.component.ts
src/app/mailviewer/rmm7messageactions.ts
src/app/rmmapi/rbwebmail.ts

Fixes issues with displayed folder counts being incorrect after message moves (including to spam/trash) - intermittent issue that happens when a move is made when an index sync is also in progress

fix(maillist): Ensure actions involving 2 folders update counts on both

---

src/app/app.component.ts
src/app/canvastable/canvastable.ts

The main tweak here is that after updating the new set of rows (MessageDisplay content in the canvastable) we force an update of the canvastable "topindex", which will have changed when messages are removed from the current folder. Why exactly this works fine in other circumstances.... I'm not sure!
Fixes blank-list issue

fix(mailviewer): Update maillist after delete/move

---

src/app/mailviewer/singlemailviewer.component.ts

Whoops - Previous changes made all image attachments disappear in HTML, whether they were displayed inline in the HTML or not. Here we actually check whether the HTML contains the image, and then act accordingly.

fix(mailviewer): Display image attachments in HTML unless inline

---

src/app/login/login.component.html

Input mode was set to numeric, so it didn't allow the user to type in letters. Changed to standard input mode.
Fixes #1059

fix(login) Allow normal text in OTP input

---

src/app/mailviewer/singlemailviewer.component.css

Improves issue #1072.
The horizontal scroll is visible now, but it appears on the very bottom of the message. It's a temporary fix while I'm still looking for a way to show it regardless of the message height.
It is possible to scroll easily on a touchpad. With a mouse I believe you'd have to scroll to the bottom of your email.

fix(mailviewer): Add horizontal scroll to message view

---

src/app/compose/draftdesk.service.ts
src/app/mailviewer/singlemailviewer.component.html
src/app/mailviewer/singlemailviewer.component.ts

Fixes #235 
Created a reply header for HTML messages. It didn't exist, we used the same header for everything. Now it looks like this:
<kbd><img src="https://i.imgur.com/C3Awhb0.png"></kbd>
Improved header for forwarding HTML messages, looks like this:
<kbd><img src="https://i.imgur.com/nPpvREC.png"></kbd>

FIX for #235 "Reply header" missing separators or spaces

---

src/app/account-app/account-renewals.component.html
src/app/account-app/account-renewals.component.ts
src/styles.scss

- Removed the option to expand subscription details and made it static. It didn't work properly.
- Made table indentation smaller on mobile screens.
- Changed font to not bold in the details section.
- Added background color to the header of each product (used the color from the top bar where hamburger menu is).
- Made the product header font bold.
- Removed small icon indicators.
Fixes #1116 
Before: [One](https://i.imgur.com/NnDuax0.png), [Two](https://i.imgur.com/RESxigj.png)
Now:
<kbd><img src="https://i.imgur.com/sN99hqU.png" width="350"></kbd> . <kbd><img src="https://i.imgur.com/D7bFW9r.png" width="350"></kbd>

fix(your-subscriptions): Make subscriptions table usable on small screens

---

src/app/account-app/stripe-payment-dialog.component.html

Fixes: #831 
Improved a bit to be able to close issue.
Made the fonts smaller on mobile, and reduced size of the card logos image. 
This way everything looks like it actually fits.
<kbd><img src="https://i.imgur.com/p0iBbbs.png"><kbd>

fix(credit-cards): Improve the look of payment forms on mobile

---

src/app/mailviewer/singlemailviewer.component.ts

Improves: #234 
Fixes sentry errors about this part of code.
Unfortunately the header still rarely renders as undefined. This fix does improve this issue a lot though. 
I'm working on figuring out why this is happening.

fix(mailviewer): Properly show reply and forward headers for HTML messages

---

src/app/app.component.html
src/app/app.component.ts

Fixes #1162 by checking width properly before setting if to put on the single mail view on side or bottom before it is set and saved in localStorage as before. Also uses the newer API for width check, making it one of the first to use it very demonstrably in app flow. Could be possible to tidy up to look nicer/more concise, but regardless it works from personal testing. Test with another platform such as Mac first ( @gtandersen ?) before merge though.

Fix default orientation when not set on narrow width

---

src/app/account-app/account-transactions.component.html
src/styles.scss

Fixes #827 
Removes the vertical whitespace on the bottom of every row and reduces indentations on the sides on mobile.
Mobile: [before](https://i.imgur.com/u69guMI.png) -> [after](https://i.imgur.com/VgeG28O.png)
Desktop: [before](https://i.imgur.com/y4ODFAA.png) -> [after](https://i.imgur.com/GIwk41y.png)

fix(payment-history): Remove whitespace in payment rows

---

src/app/app.component.ts
src/app/common/messageinfo.spec.ts
src/app/folder/folderlist.component.spec.ts
src/app/folder/folderlist.component.ts
src/app/mailviewer/rmm7messageactions.ts
src/app/messagetable/messagetablerow.ts
src/app/rmmapi/messagelist.service.ts
src/app/rmmapi/rbwebmail.spec.ts
src/app/rmmapi/rbwebmail.ts
src/app/xapian/search-expression-builder/search-expression-builder.component.ts
src/app/xapian/searchservice.spec.ts
src/app/xapian/searchservice.ts

1. Messages with future message dates would cause the index updating to stop (as it was then fetching "messages changed after 2038" for example) - fixed by ensuring message fetching compares change dates no later than the current time.
2. Sub-Folder paths were in some places stored/used with a "/" separator, and in some with a "." As "." is officially used, and we don't display the names (except for in the url when bookmarking a folder), this is changed to be "." everywhere. This was likely causing folder count errors (storing counts as "." path, but reading out as "/" path).
3. Fixed tests to correctly send message times in seconds, not milli seconds (they broke after implementing no1)

Cope with far future dates, folder separators always a "."

---

src/app/app.component.ts
src/app/xapian/searchservice.spec.ts
src/app/xapian/searchservice.ts

Previously, if indexing was on, we would load initial an message list
from the REST api, then start loading any previously stored index
files. The stored index file contents were then displayed (likely
older than the REST api contents), then we would fetch message updates
from the api, add those in, and update the display again.
This change removes the "display update" after stored index loading,
and before fetching new updates. Thus we continue to display the
latest set of messages at all times, while starting up.
Fixes #843

fix(loading): Complete index load before displaying list from index

---

src/app/app.component.ts
src/app/canvastable/canvastable.ts
src/app/folder/folderlist.component.ts
src/app/rmmapi/messagelist.service.ts

2nd try - more places where we were refreshing the list before the
index was finished found and removed.
Add more robustness to canvastable when .rows not set yet.

fix(loading): Only refresh message list after index loaded

---

src/app/app.component.ts
src/app/canvastable/canvastable.ts
src/app/folder/folderlist.component.ts
src/app/rmmapi/messagelist.service.ts
src/app/xapian/searchservice.ts

We weren't coping with loading fresh accounts indexes from accounts with only one set of partitions - fixed.

fix(loading): Only refresh message list after index loaded (updated)

---

src/app/common/messagelist.ts
src/app/websocketsearch/websocketsearchmaillist.ts
src/app/xapian/searchmessagedisplay.ts

- Changed order of the Folder column to be able to freely resize the Size column. This way the flag columns aren't getting in the way.
- Fixed the Size column alignment. Now it's aligned to the left like everything else.
Close #1126

Fix Size and Folder columns issues

---

src/app/canvastable/canvastable.ts

Fixes: #795 
Now this type of cursor will only show outside of wrap mode.

fix(canvastable): Don't show column resizing cursor while in wrap mode

---

src/app/mailviewer/singlemailviewer.component.html
src/app/mailviewer/singlemailviewer.component.ts
src/app/rmmapi/messagecache.ts

Not loading external image src URLs means the HTML mail view loads
faster, and we also do not load "tracking" images embedded in emails.
Currently this displays a "show images" checkbox (next to the HTML one), which defaults to off and cannot be set to "always". Ideas on defaults/implementation welcome. (Personally am tempted to make it an "always allow for this sender" rather than global on/off)
Fixes #31

feature(mailviewer): Do not load external HTML images unless asked

---

src/app/mailviewer/singlemailviewer.component.ts

Previous implementation replaced default html with "html with no images" and deployment of only the backend meant users were seeing grey'ed out external images with no way to show the external images.
This update switches the default so that "with images" is sent as default from the backend, and then we implement the "dont show images by default" magic

fix(mailviewer): Ensure html-images-feature doesn't break existing

---

src/app/mailviewer/singlemailviewer.component.ts

RFC compliant messages *must* have a Date header, however now we've found one that doesn't - default it to 1970 so that we can display it anyway
Fixes: #1065

fix(mailviewer): Default dates to 1970 where not supplied

---

src/app/contacts-app/contact.spec.ts
src/app/contacts-app/contact.ts
src/app/contacts-app/contacts-app.component.ts
src/app/contacts-app/contacts.service.ts
src/app/mailviewer/singlemailviewer.component.html
src/app/mailviewer/singlemailviewer.component.spec.ts
src/app/mailviewer/singlemailviewer.component.ts

The recent new feature to only show external images (et al) when
requested, implemented to speed up HTML display, is annoying some users.
This improvement allows users to save the "show external html images"
per sender (stored as a separate contact type in the dav contacts).
A new contact is only created if they do not already exist.
If/when the user later creates a contact with the same email as the
hidden type, we re-use the same contact and change it to the
"individual" type so that it will be displayed in Contacts.
Fixes #1249

feature(mailviewer): Store "show html images" per sender

---

e2e/cypress/integration/compose.ts
src/app/contacts-app/contact.ts
src/app/contacts-app/contacts.service.ts
src/app/dialog/htmlconfirm.dialog.ts
src/app/mailviewer/mailviewer.module.ts
src/app/mailviewer/singlemailviewer.component.html
src/app/mailviewer/singlemailviewer.component.ts

Attempt #2: Allow choice of storing HTML Always/Per sender/with/without images
Fixes #1249

feature(mailviewer): More control on how html/image settings are stored

---

src/app/mailviewer/singlemailviewer.component.ts

This just adds a dump to console so that we can better hunt a
recurring error.

refactor(mailviewer): Improving the errors when an email won't load

---

backend-proxy-mock.conf.js
e2e/cypress/integration/mailviewer.ts
e2e/mockserver/mockserver.ts
src/app/app.component.ts
src/app/compose/compose.component.ts
src/app/mailviewer/singlemailviewer.component.ts
src/app/rmmapi/rbwebmail.ts
src/app/rmmapi/rmmhttpinterceptor.service.ts
src/app/xapian/searchservice.ts

Instead of "object Object". This sorts out all the instances where
"getMessageContents" might return an error for a number of ways.
Fixes: #1262

fix(mailviewer): Output mail load error message strings

---

src/app/compose/compose.component.html
src/app/compose/compose.component.ts

The problem: Dragging & dropping files onto the compose window would pop up the "drop files here" box, then appear to do nothing for 30secs or longer, then draw the progress bar / visually upload the file.
The solution: Folks on t'internet seem many have issues with this, I pulled the most used solution, which is to have the drag/drop events processed "outside angular" (using the zone object), which seems to speed everything up.
Also added a bunch of guards, and prevented it from bubbling the event up (down?) the chain of elements, as it was trying to run the check files / upload files maaaany times.
Fixes #1070

fix(compose): Speed up drag&drop of attachments onto compose editor

---

src/app/rmmapi/rbwebmail.ts
src/app/xapian/searchservice.spec.ts
src/app/xapian/searchservice.ts

This enhances previous code that only checked the index counts against
the rest api counts. Now we also check non-indexed folders (Spam/Trash)
stored folder count values against actual counts.
Needs a rest api update
Fixes #1182

fix(folderlist): Check current folder counts for all folder types

---

src/app/app.component.ts
src/app/folder/folderlist.component.ts
src/app/rmmapi/rbwebmail.ts

Always use "priority" for sorting folders, instead of only when "move"
sorts them. Create sends a priorities order into which the newly
created folder can be inserted.
Sorting via priorities (or alphabetically) is now handled on the
backend inside the "list" endpoint. This ensures that new folders
created using RMM6 also do not appear above Inbox.
Fixes #1099

fix(folders): Ensure creating a new folder does not show above Inbox

---

src/app/app.component.ts
src/app/xapian/searchservice.ts

A frontend addressing of an issue in [internal issues] 1177 and 1178, verifying via a isInteger filter that the functions which call move_messages and and verifymessages for the searchindex that message IDs given are valid integers. Number.isInteger will return true on valid integer numbers (including 0) but false on empty/NaN values, ensuring at least they are valid integers before they are given to the API. The is because it doesn't otherwise check in the arrays (or array of objects) that the message ID's are valid.
This issue has also been addressed in the backend, but this is for consistency and cutting down redundant API calls that are found already invalid.
From a npm start and reporting existing spam mail in my SC mailbox it appears to function as frontend behaves and general usage …

Checks the msg IDs given to API for certain endpoints are valid

---

src/app/calendar-app/calendar-app.component.html
src/styles.scss

Adds a link to the Caldav calendar syncing help as per #805 and appears as below in a new tab. Required some CSS tweaks as mat-list-item wasn't correctly taking certain custom styles in styles.css due to being used as an attribute to an anchor (as per angular docs specify it to be done for links).
Name of link is simply a first pass guess for "this is a guide on how to sync with Caldav" to avoid obscurity/confusion on the link purpose.

Adds a link to caldav sync guide on calendar

---

src/build/build-changelog.js

In which we only output correctly formatted entries.
Fixes #1318

fix(changelog): Ensure typos in commit entries do not break the page

---

src/app/rmmapi/rbwebmail.ts

We cache requests for message contents, if the request turns out to fail we should delete both copies so that it is refetched
Improves #1309

fix(messaging): Delete both copys of an HTTP request if it fails

---

src/app/compose/compose.component.ts
src/app/compose/draftdesk.service.spec.ts
src/app/compose/draftdesk.service.ts
src/app/mailviewer/singlemailviewer.component.html
src/app/mailviewer/singlemailviewer.component.spec.ts
src/app/mailviewer/singlemailviewer.component.ts
tsconfig.json

Fixes #234
For reasons best known to history, we were "generating" the reply/fwd headers (where header means "first line(s) of message" in the mail viewer template, then copying them out when doing a reply or fwd action. As pointed out in the #234 thread, quick actions could mean a message was opened, and the "reply" button clicked, before the reply header was generated, leading to "undefined" header strings.
I have moved the generation out of the template, and into the "create draft" code (which has the same mail object). Which means we could also now "reply" without opening a message, if we wanted to.
I also made the HTML+Text reply headers match, as one was regenerated differently!

fix(compose): Generate Reply/Fwd header text only when needed

---

src/app/app.component.html
src/app/mailviewer/singlemailviewer.component.html

Mark as read and unread, respectively:
Ref: https://community.runbox.com/t/confusing-mark-as-read-unread-icons/1937/3?u=geir

style(mail menu): Improve read and unread icons.

---

src/app/app.component.html

Currently tooltips show at the bottom of the button, blocking the button bellow it.
Because of some weird behaviour, the tooltip does not vanish when you move off it. This is probably due to an outdated material version, because when reviewing the official examples I do not experience the same behaviour
https://v6.material.angular.io/components/tooltip/overview
As a temporary fix, I have moved the tooltips to the left.
See https://github.com/runbox/runbox7/issues/1439

fix(tooltips): Move context tool button tooltips to the left side

---

src/app/rmmapi/rbwebmail.ts
src/app/rmmapi/rmmauthguard.service.ts
src/app/rmmapi/rmmhttpinterceptor.service.ts
src/app/xapian/searchservice.ts

Expired accounts should only be able to visit account/subscriptions (and related pages) to process a renewal. This prevents starting the index updates or current message list, as these will delete the session cookie when called with an expired account, which prevents the user from visiting the subscriptions page.
Fixes #1473

fix(account): Only subscription/renewal pages for expired accounts

---

src/app/rmmapi/rmmauthguard.service.ts
src/app/rmmapi/rmmhttpinterceptor.service.ts

Expired accounts should only be able to visit account/subscriptions, attempting to view anything else should return them to account/subscriptions

fix(accounts): Subscriptions links on account expiry

---

src/app/xapian/searchservice.ts

Fixes #1485
When no search index exists, then we should not attempt to fetch partitions, and we should restart the message list update mechanism. We should definitely not try and twiddle a setting on the xapian index that didn't load (!)

fix(search): Cope with no index, use websocket and message fetch

---

src/app/xapian/searchservice.ts

There are many sentry-errors resulting from the message list drawing code attempting to fetch the message contents from the cache, when the cache hasnt been created or updated yet (that happens after the canvas has been painted with the message list)
This fills the cache as we look for the data (using promises so without interrupting the canvas drawing)

fix(messagecache): Load message contents whenever we encounter them

---

src/app/account-app/account-product.component.html
src/app/account-app/account-product.component.ts
src/app/account-app/account-upgrades.component.html
src/app/account-app/account-upgrades.component.ts

The subscribe to the "me" object sometimes finishes after the "products", so current_sub, used to set the is_upgrade/is_downgrade flags isnt always set when needed. Ensure that the me.subscription is run after the products, then set the current_sub

fix(account): Ensure upgrade/downgrade works when returning to page

---

src/app/compose/compose.component.ts

fromSubjects is now a list of profileService Identity objects, "name" is the identity description, "from_name" is the chosen name string to send using

fix(compose): Use from-name when sending email, not identity name

---

src/app/folder/folderlist.component.css
src/styles.scss

More subtle unread count badges that align better with the numbers without truncating them:
Better aligned expand/collapse icons (especially Safari):
Better aligned Settings menu icons (especially Safari):

style(mail): Improve unread count badges and icon alignments.

---

src/app/compose/compose.component.ts

fix(compose): Add plain text signatures when replying to HTML email

---

src/app/compose/compose.component.ts

When choosing a different identity in compose, swap to using the 2nd identities signature (if email not yet edited)

fix(compose): Swap identity signature in HTML mode

---

src/app/compose/recipients.service.spec.ts
src/app/mailviewer/singlemailviewer.component.spec.ts
src/app/profiles/profile.service.spec.ts
src/app/profiles/profile.service.ts
src/app/profiles/profiles.editor.modal.html
src/app/profiles/profiles.editor.modal.ts

Broken by recent identities changes, alias identities should be allowed to change their "preferred domain", eg from runbox.com to runbox.uk

fix(identities): Re-enable editing of preferred domain for aliases

---

src/app/profiles/profiles.editor.modal.html

Allows users to change their preferred "runbox domain" (eg from runbox.com to runbox.uk) for any Identities not using virtual domains, without requiring new validation. For username identities this is a drop-down to choose the new domain (localpart may not be changed), for other identities the entire email may be changed, we only require validation if a non-runbox domain is used.

feat(identities): Change of runbox domains for all identities

---

src/app/profiles/profiles.component.html

.. It was missing entirely if the user had no "Other" identities (including the "Add Identity" button), which made it difficult to add any!

fix(identities): Always displays Other identites section

---

src/app/app.component.ts
src/app/contacts-app/contacts.service.spec.ts
src/app/xapian/searchservice.ts

Server-side indexes are not created instantly for new users, so if a user signs up, then accepts the offered index download prompt, it would fail. This PR catches the "fail" and creates a new index in the browser, which is then updated as usual by index updates.
The check for server side index is repeated any time the user stops the synchronisation and restarts it, if there is still no server side index, we create another local one and add any updates from scratch again.

Create browser-local index if server-side not found

---

src/styles.scss

Make default link color the same as link theme color and not browser default.

feat(a11y): Remove underline on anchor hover

---

src/app/app.component.ts
src/app/rmmapi/messagelist.service.ts
src/app/xapian/index.worker.ts
src/app/xapian/searchservice.ts

Only switch to index data after its actually loaded, don't accidentally switch back to the API messagelist., or redo folder counts until user actions are finished.
Also fix an issue where switching from non-folders (Compose/Drafts/Overview) to a folder (by clicking on the Folder name), would display the contents of Inbox, regardless of which folder was selected.
Seems the issue was childRouteActivated - runs when the non-folder router outlet (aka compose, drafts et al) deactivates, and was setting selectedFolder to Inbox, generally *after* switchToFolder et al had switched the folder (so we switched it to chosen folder, then back to Inbox after the deactivation)
Fixes: #1622 
Fixes: #1564

fix(maillist): Ensure we only switch to index data after its loaded

---

src/app/xapian/searchservice.ts

At some point we lost this - it does restart itself eventually (after user actions) - better to restart explicitly though

fix(index): Restart index updates after syncing index

---

e2e/cypress/integration/mailviewer.ts
e2e/cypress/integration/message-caching.ts
e2e/mockserver/mockserver.ts
src/app/account-app/bitpay-payment-dialog.component.html
src/app/app.component.ts
src/app/mailviewer/mailviewer.module.ts
src/app/mailviewer/singlemailviewer.component.html
src/app/mailviewer/singlemailviewer.component.ts
src/app/rmmapi/lru-message-cache.ts
src/app/rmmapi/messagecache.ts
src/app/rmmapi/rbwebmail.spec.ts
src/app/rmmapi/rbwebmail.ts
src/app/xapian/index.worker.ts
src/app/xapian/searchservice.spec.ts
src/app/xapian/searchservice.ts

On canvas update, fetch all in-view message contents at once (instead of one request per message), .. if not already in the cache. After fetching, update the index (to add the message contents to the index), for all the fetched messages at once, making less data exchanges between the two threads.
This should mean less busy threads and more prompt actions for users

Updates bulk messages PR, adding index working (less data passing) improvements

---

src/app/canvastable/canvastable.component.html
src/app/canvastable/canvastable.ts
src/app/folder/folderlist.component.ts

This was "fun with browsers and standards" time, chrome needs the canvas-to-copy to be in the DOM (MDN/firefox doesnt), either way whats used as the dragimage is the, view of the element as the user would see it.. so we were seeing whatever  was displaying where the dragcanvas element was being created (which was the top of the main canvas).
Fixed by creating the canvas-copy in the code, and adding it to the DOM off the left edge (off the top doesnt work in all browsers... standards!) 
Fixes: #1095

fix(drag): Shows correct drag-image while moving images to folders

---

src/app/canvastable/canvastable.ts

The existing canvas already restyles its height/width using devicePixelRatio (which is 2 on hidpi screens, and the ratio when zooming in), so we need to copy data to the dragImage using the multiplied values.
Tested with zoom on chrome/ff on linux, no retina screens available
Fixes: #33

fix(messagelist): Correct drag images for hidpi screens/zoomed in

---

src/app/mailviewer/rmm7messageactions.ts
src/app/mailviewer/singlemailviewer.component.html
src/app/rmmapi/rbwebmail.ts

feat(mailviewer): New allowlist sender option for mail viewer

---

src/app/compose/compose.component.ts
src/app/compose/draftdesk.component.ts

Fixes: #644
@antoniskalou did this as a commit a while ago, somehow we lost / didnt apply it!
Also removed, bonus call to updateDraftsInView which isn't needed as its already called in a subscription to changes: draftDeskservice.draftModels.subscribe

fix(compose): Stop creating new draft copies after sending

---

src/app/account-app/account-upgrades.component.html
src/app/account-app/account-upgrades.component.ts

Existing code assumed the user's current subscription was one of the possible account upgrades - this isn't the case, so now we fetch the current sub separately. Also ensures any page parts that use the current subscription check it is loaded before applying calculations to it

fix(upgrades): Fetch the correct current subscription for the user

---

src/app/account-app/credit-cards/stripe-add-card-dialog.component.html
src/app/account-app/credit-cards/stripe-add-card-dialog.component.ts
src/app/account-app/payments.service.ts
src/app/account-app/stripe-payment-dialog.component.html
src/app/account-app/stripe-payment-dialog.component.ts
src/app/rmmapi/rbwebmail.ts

Switches from card elements to "payment element" which draws all the card fields for us, it will also allow the customer to use Link, PayPal, Apple Pay and Google Pay (if enabled in Stripe), as well as re-use saved card details
Notes / implementation details:
* I am switching the implementation from "card elements" to "payment element", this is a recommended upgrade
* The actual version of the SDK in-use by backend API calls is set in the stripe account, my backend patch adds a way to change it via the API call for testing.
* we are using (for which I cannot find reasons), the deferred payment (collect details, then create payment intent), and the finalize payments on the server functionality I am keeping this in case there were reasons
* This all works apart from: Enabling the "re-use …

fix(payments): Upgrade to latest version of Stripe SDK

---

src/app/folder/folderlist.component.html
src/app/folder/folderlist.component.scss
src/app/folder/folderlist.component.ts

It is currently not possible to select a folder using the keyboard. Considering this is a primary use-case I decided to fix it as one of the first a11y improvements.

Make folder buttons keyboard navigable

---

.github/workflows/ci.yml

The node action already does caching of the .npm
directory.

build(ci): Remove redundant cache action

---

src/app/account-details/personal-details.component.ts

Issue was likely caused by an error that was thrown between the default true value of the `is_alternative_email_validated` and the request response callback.
- Decided to have as default that the alt email was not validated.
- Added a null check that was likely the reason for the error.
#1510 specifically https://github.com/runbox/runbox7/issues/1510#issuecomment-2697748691

fix(details): show alternative email resend on email change

---

src/app/login/login.component.html

Remove the empty redundant ngModel directive.

fix(login): make username and password required
