src/app/folder/folderlist.component.html, src/app/folder/folderlist.component.spec.ts, src/app/folder/folderlist.component.ts, src/app/rmmapi/rbwebmail.ts
Added functionality and test case for empty trash. The empty trash button is located under the "More" folder actions button.
=> folderlist: Added function for Empty Trash #7

src/styles.scss
=> fix: Allow clicking message list scrollbar behind message action buttons.

src/app/app.component.ts
Small change to avoid switching to conversation view if there's only one message in the thread (#21)
=> conversation-view: #21 don't go to conversation view if just one message

angular.json, backend-proxy-mock.conf.js, e2e/compose/compose.e2e-spec.ts, e2e/compose/compose.po.ts, package.json, src/app/rmmapi/rmmhttpinterceptor.service.ts
This is about running end 2 end (e2e) tests for testing the full application. Also include a simple mock backend for light development and for automating the e2e tests without having to use real accounts / servers.
=> compose: End 2 End (e2e) test setup

e2e/domainregister/domainregister.e2e-spec.ts, e2e/domainregister/domainregister.po.ts, e2e/login/login.e2e-spec.ts, e2e/login/login.po.ts, e2e/mockserver/mockserver.ts, src/app/domainregister/domainregister.component.ts, src/app/login/login.component.ts, src/app/rmmapi/rmmhttpinterceptor.service.ts
Also added to e2e test for ensuring progress bar is showing
Also note the domain-register lint-compliance and e2e test @hernan604
=> login: fix progressbar not showing after clicking login

src/app/domainregister/domainregister.component.ts
added missing .pipe() for timeout()
=> added missing .pipe() for timeout()

src/app/domainregister/domainregister.component.html
Hide "Register new domain" tab when user is in
- renewal mode
- purchase privacy mode
=> Hide "Register new domain" tab when user is in renewal mode

e2e/search/multiplesearchinput.e2e-spec.ts, src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/xapian/multiple-search-fields-input/multiple-search-fields-input.component.html, src/app/xapian/multiple-search-fields-input/multiple-search-fields-input.component.spec.ts, src/app/xapian/multiple-search-fields-input/multiple-search-fields-input.component.ts, src/app/xapian/multiple-search-fields-input/multiple-search-fields-input.module.ts
This adds an "advanced search" panel like in RMM6, with multiple search input fields for folder, subject, from, to, date etc.
=> search: multiple search fields panel ( #88 )

src/app/app.component.html, src/app/app.component.ts, src/app/mailviewer/singlemailviewer.component.html, src/app/mailviewer/singlemailviewer.component.spec.ts, src/app/mailviewer/singlemailviewer.component.ts
- for reporting "Not spam"
- for lising contents of designated spam folder
=> bugfix: #86 support designated spam folders

ngsw-config.json
This makes the folder list available also when offline.
=> Cache folderlist when offline

src/app/app.component.html
=> fix: Keep folder pane open when clicking to stop/start index synchronization.

src/app/calendar-app/calendar-app.component.html
This takes us from this:
To this:
=> Calendar: make the day view more detailed

src/styles.scss
=> fix(styling): stop 3-digit+ new message counts from being truncated

src/app/calendar-app/calendar-app.component.ts
=> fix(Calendar): remove calendar events when we delete the calendar itself

src/app/calendar-app/calendar-editor-dialog.component.ts, src/app/calendar-app/delete-confirmation-dialog.component.ts, src/app/calendar-app/event-editor-dialog.component.ts
Ideally we'd offer to delete just a single occurence, but that won't be
possible until GH-174 is implemented.
=> fix(Calendar): Show additional confirmation when deleting a recurring event

src/app/mailviewer/singlemailviewer.component.html, src/app/mailviewer/singlemailviewer.component.spec.ts, src/app/mailviewer/singlemailviewer.component.ts
add download/thumbnail support for encrypted messages
add html support for encrypted messages
unit test for attachments download urls
=> feat(pgp): parse html and attachments

src/app/calendar-app/calendar-app.component.html, src/app/calendar-app/calendar-app.component.ts, src/app/calendar-app/event-editor-dialog.component.ts
Visible dynamically, on mousehover
Demo:
=> feat(Calendar): Add buttons to add new event on each day

src/app/contacts-app/contact-details/contact-details.component.html, src/app/contacts-app/contacts-app.component.css, src/app/contacts-app/contacts-app.component.html, src/app/contacts-app/contacts-app.component.ts, src/app/contacts-app/contacts-settings.component.html, src/app/contacts-app/contacts-welcome.component.ts, src/styles.scss
Adjustments to left pane, textual content, and buttons.
=> fix: Improve layout and formatting of Contacts screens

src/app/calendar-app/calendar-app.component.spec.ts, src/app/calendar-app/runbox-calendar-event.ts
=> fix(Calendar): Don't break event start date when adding recurrence to it

README.md
=> docs: Add information about how to acquire a Runbox account. 

src/app/calendar-app/calendar-app.component.html, src/app/calendar-app/calendar-app.component.spec.ts, src/app/calendar-app/event-editor-dialog.component.html, src/styles.scss
This is my attempt to un-conflict https://github.com/runbox/runbox7/pull/191 – I also refactored the CSS a little in an attempt to merge it cleanly, including renaming some classes to (hopefully) make them better describe what they configure.
@gtandersen let me know if that looks okay to you and if I haven't forgotten anything :)
=> Tadzik/fix for/gtandersen fix calendar layout

src/app/calendar-app/calendar-app.component.html, src/app/calendar-app/event-editor-dialog.component.html, src/styles.scss
- Even calendar columns.
- Decrease event font size to fit more text in each square.
- Decrease sidenav width.
- Increase title font size.
- Decrease Add Event height.
=> fix: Improve layout and formatting of Month view and Add Event view.

angular.json, package-lock.json, package.json, src/app/compose/compose.component.ts
- upgrade tinymce
- load plugins from bundled assets instead of external _js folder
- add more plugins and toolbar buttnos to compose tinymce config
fixes issue #6
=> feat(compose): enable more tinymce features

src/app/compose/compose.component.ts, src/app/dialog/dialog.module.ts, src/app/dialog/dialog.service.ts
add popup progress spinner when pressing send button
fixes #182
=> feat(compose): progress spinner on send

src/app/account-app/account-product.component.html, src/app/account-app/account-upgrades.component.html, src/app/account-app/payment-method.component.ts, src/app/account-app/shopping-cart.component.html, src/app/menu/headertoolbar.component.html, src/styles.scss
- Correct text referring to up- and downgrades.
- Make 3-year special offer more prominent.
- Use accent color on Runbox 6 main menu item.
=> style(payment): Improve layout and formatting.

e2e/compose/compose.e2e-spec.ts, e2e/compose/compose.po.ts, e2e/folders/folders.e2e-spec.ts, e2e/folders/folders.po.ts, src/app/dialog/simpleinput.dialog.ts, src/app/folder/folderlist.component.html
Add an e2e test for checking the email title changes to the subject text & test for creating folder at root level
=> test(e2e): extra compose test and root folder creation

src/app/app.component.html
@gtandersen I think that just about covers it :)
=> fix(email-app): Hide the message panel when in compose/drafts

package-lock.json, package.json, src/app/calendar-app/calendar.service.spec.ts, src/app/compose/recipients.service.spec.ts, src/app/contacts-app/contact-details/contact-details.component.spec.ts, tslint.json
It also adds a custom tslint rule that will disallow commiting
a limited test suite (fit, fdescribe etc) in the future.
=> test(all): make sure *all* tests are running again

package-lock.json, package.json, src/app/calendar-app/calendar.service.spec.ts, src/app/compose/recipients.service.spec.ts, src/app/contacts-app/contact-details/contact-details.component.spec.ts, src/app/login/login.component.ts, tslint.json
I based this on https://github.com/runbox/runbox7/pull/330 to make sure the tests are actually ran :)
https://github.com/runbox/runbox7/pull/332/commits/0a5168077693ce23d97183d16311db504532c8b9 is the relevant commit here.
=> Show errors on failed login

src/app/account-app/stripe-payment-dialog.component.html, src/app/account-app/stripe-payment-dialog.component.ts
This fixes Apple Pay and others.
=> fix(account-app): Implement the missing bits of PaymentRequest handling

src/app/app.component.html, src/app/app.component.ts
Needs a way to add it back when removed by accident. @gtandersen, any idea for a good place to add the setting?
=> feat(webmail): Add an option to hide the message pane

src/app/account-app/account-app.module.ts, src/app/account-app/account-receipt.component.html, src/app/account-app/account-renewals.component.html, src/app/account-app/account-transactions.component.html, src/app/account-app/account-transactions.component.ts, src/app/account-app/account-upgrades.component.html, src/app/account-app/payments.service.ts, src/app/account-app/shopping-cart.component.html, src/app/account-app/shopping-cart.component.ts, src/app/common/common.module.ts, src/app/common/loading.component.ts, src/app/rmmapi/rbwebmail.ts
This will hopefully alleviate some of the shopping cart issues.
=> Payment improvements

src/app/compose/compose.component.ts, src/app/compose/draftdesk.service.ts
Fixes https://github.com/runbox/runbox7/issues/267
=> Fix for GH-267

.travis.yml, CONTRIBUTING.md, README.md, package.json, run-ci-tests.js
This way all the tests can be run at once with the same settings that will be used by Travis.
=> feat(tests): Add a ci-runner script and use it in Travis settings

package-lock.json, package.json, src/app/app.component.ts, src/app/app.module.ts, src/app/canvastable/canvastable.ts, src/app/folder/folderlist.component.spec.ts, src/app/folder/folderlist.component.ts
j go “down” the list
k go “up” the list
gi go to inbox
gt go to sent messages
=> feat(HomePage): Add keyboard shortcuts

src/app/rmmapi/rmmauthguard.service.ts, src/app/rmmapi/rmmhttpinterceptor.service.ts
We don't want to kick them out if they're in the middle of paying
=> fix(authguard): don't push users out to login if they're merely expired

src/app/contacts-app/contacts-app.component.html, src/app/contacts-app/contacts-app.component.ts, src/app/menu/sidenav-menu.component.ts
It's noisy for now as it's based on tadzik/mobile-calendar.
=> WIP: mobile view for contacts

CONTRIBUTING.md
This integrates an updated version of https://github.com/runbox/runbox7/pull/203
=> docs(contributing): Update TOC

src/app/contacts-app/contact-details/contact-details.component.html, src/app/contacts-app/contact-details/contact-details.component.ts, src/app/contacts-app/contact-details/formarray-editor.component.html, src/app/contacts-app/contacts-app.component.html, src/app/contacts-app/contacts-app.component.ts, src/app/contacts-app/contacts-app.module.ts, src/app/contacts-app/contacts.service.ts, src/app/rmmapi/rbwebmail.ts, src/styles.scss
Including:
* better mobile view
* ability to select/delete multiple contacts
* bugfix that caused wrong data to appear when switching between contacts (introduced in d4c2d760ce6d3433f18140e86df6fdd47955c109)
=> Contacts improvements

src/app/login/login.component.html, src/styles.scss
=> style(login): Improve layout of login area. Move progress bar to footer.

src/app/app.component.ts, src/app/canvastable/canvastable.ts
This also makes it more vim-like, going one row at a time.
=> fix(canvastable): Fix scrolling with keyboard bindings

src/app/account-app/account-product.component.html, src/app/account-app/account-product.component.ts, src/app/account-app/account-upgrades.component.ts, src/styles.scss
This basically turns them into manually-managed radiobuttons.
Looks like this:
=> feat(account-products): Only allow one subscription order at a time

package-lock.json, package.json, src/app/contacts-app/contact-details/formarray-editor.component.html
Needs to be under the same formArray that displays types.
=> fix(contacts): Make the address form display correctly

src/app/account-app/account-components.component.html, src/app/account-app/account-product.component.html, src/app/account-app/account-product.component.ts, src/app/account-app/account-upgrades.component.html, src/app/account-app/account-upgrades.component.ts, src/app/account-app/cart.service.ts, src/app/account-app/payments.service.ts, src/app/account-app/product.ts, src/app/account-app/shopping-cart.component.html, src/app/account-app/shopping-cart.component.ts, src/app/rmmapi/rbwebmail.ts
Apart from fixing minor bugs and style fixes, this also helps the user purchase the right stuff if they need to.
Some screenshots:
Comments are welcome. I'm not super happy with the code architecture (particularly keeping PIDs hardwired in the CartService), so any ideas on how to improve it will be appreciated.
=> Payment UI improvements

cypress.json
Hopefully it will make Travis fail us less often
=> ci(cypress): Increase the default command timeout

src/app/contacts-app/contact-details/formarray-editor.component.html
=> fix(contacts): Add a missing button to delete contacts' address

src/app/compose/compose.component.html, src/app/compose/compose.component.ts
=> feat(compose): Add a button to cancel attachment upload

src/app/contacts-app/contacts-app.component.ts
This should make us more descriptive than "Internal server error" in some cases.
=> fix(contacts): Catch a wider variety of backend errors

src/app/contacts-app/contact-details/contact-details.component.html, src/app/contacts-app/contact-details/contact-details.component.ts, src/app/contacts-app/contacts-app.component.html, src/app/contacts-app/contacts-app.component.ts, src/app/contacts-app/contacts.service.ts, src/app/contacts-app/vcf-import-dialog.component.html, src/app/contacts-app/vcf-import-dialog.component.ts
What was contact groups are now categories, to align with the vCard
format correctly
Closes #510
=> fix(contacts): Rename "groups" to "categories"

src/app/domainregister/domainregister.component.ts
This should fix domreg component in runbox6
=> fix(domreg): Eliminate rmmapi dependency in domreg

e2e/cypress/plugins/index.js, e2e/cypress/support/index.js, package-lock.json, package.json
Outputs more detail on failing e2e tests to screen/console.
=> build: Add terminal debugging for headless systems

src/app/contacts-app/contacts-app.component.ts
Refuse to import contact if a uid matches any existing one.
=> fix(contacts): Don't import contact if already present

src/app/compose/compose.component.html, src/app/compose/compose.component.ts, src/app/compose/draftdesk.service.spec.ts, src/app/compose/draftdesk.service.ts, src/app/compose/emailvalidator.ts, src/app/compose/mailrecipientinput.component.html, src/app/compose/mailrecipientinput.component.ts, src/app/rmmapi/rbwebmail.ts
All "TO" fields updated (and tests passing hopefully)
Also done: CC + BCC fields
=> 236 remove split on comma

src/app/rmmapi/messagelist.service.ts
=> fix(folderlist): Make sure we show folder counts correctly for folders not available in local index

src/app/compose/compose.component.html, src/app/compose/compose.component.scss, src/app/compose/draftdesk.component.scss, src/styles.scss
Better responsiveness and more organized layout for mobile
=> fix(compose): Make layout more responsive

src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/compose/compose.component.html, src/app/compose/compose.component.ts, src/app/compose/draftdesk.service.ts, src/app/compose/mailrecipientinput.component.html, src/app/compose/mailrecipientinput.component.ts, src/app/compose/recipients.service.spec.ts, src/app/compose/recipients.service.ts, src/app/popular-recipients/popular-recipients.component.css, src/app/popular-recipients/popular-recipients.component.html, src/app/popular-recipients/popular-recipients.component.spec.ts, src/app/popular-recipients/popular-recipients.component.ts, src/app/rmmapi/rbwebmail.ts, src/app/xapian/searchservice.ts, src/styles.scss
=> feat(compose): Show recently used recipients under input forms

e2e/cypress/integration/compose.ts, src/app/common/mailaddressinfo.spec.ts, src/app/common/mailaddressinfo.ts, src/app/compose/compose.component.ts, src/app/compose/draftdesk.service.spec.ts, src/app/compose/draftdesk.service.ts, src/app/compose/emailvalidator.ts, src/app/compose/mailrecipientinput.component.html, src/app/compose/mailrecipientinput.component.ts, src/app/compose/recipients.service.spec.ts, src/app/compose/recipients.service.ts, src/app/popular-recipients/popular-recipients.component.spec.ts, src/app/rmmapi/rbwebmail.ts, src/app/xapian/messageinfo.spec.ts, src/app/xapian/messageinfo.ts
Fixes #131 
Also refactors:
* MailAddressInfo out of messageinfo
* addRecipient* shared code into one method
=> 131 allow pasting lists of email addresses into recipient fields

src/app/compose/compose.component.ts
=> fix(compose): CC field is expanded on reply-all, if it has content

src/app/compose/draftdesk.service.spec.ts, src/app/compose/draftdesk.service.ts
=> fix(reply):Reply to all uses reply-to header if present

src/app/compose/compose.component.scss, src/app/compose/mailrecipientinput.component.html, src/styles.scss
Switch of colors for the recipients and suggestions
Issue #661
=> style(compose): Differentiate "Recently used" from recipients

src/app/contacts-app/contact-list.component.html, src/app/contacts-app/contacts-app.component.scss
=> Contacts-app fixes

src/app/account-app/account-app.module.ts
Maybe one day it will be some generic account hub, but right now let's at least make it do something useful.
Fixes GH-701
=> fix(account): Make /account show the same thing as /account/components

src/app/canvastable/canvastable.ts, src/styles.scss
When hovering over messages to indicate they can be clicked.
Fixes: #698
=> fix(canvastable): Change cursor style to "pointer"

src/app/compose/draftdesk.service.ts, src/app/rmmapi/rbwebmail.ts
Fix to prevent picking a random From address while composing a new email.
Fixes: #686
=> fix(compose): Pick correct default email

src/app/canvastable/canvastablecontainer.component.html
=> fix(canvastable): Show "select all messages" button in wrapped view

src/app/compose/draftdesk.service.ts, src/app/xapian/searchservice.ts
They cause our current, stricter build to break.
=> refactor(app): Remove some unused variables

src/app/compose/draftdesk.service.ts, src/app/rmmapi/from_address.ts, src/app/rmmapi/rbwebmail.ts
Added additional ordering using the new from_priority. 
Since all the functionality is not introduced yet, ordering by the profile type will still be used.
=> feat(profiles): Order Froms by from_priority

e2e/cypress/integration/mailviewer.ts
Delay needed for Travis CI to give it time to fully load content for tests.
=> test(mailviewer): Add a delay for reply/forwarding emails

src/app/dialog/simpleinput.dialog.ts
=> feat(dialog): Allow submitting dialogs with Enter/Return key

e2e/cypress/integration/mailviewer.ts
Another fix for Travis. 
With those delays it should have enough time to load everything.
=> test(mailviewer): Add delays for canvas to load

src/app/start/startdesk.component.html
Email, contact, calendar and task highlights weren't actual functional panels, which could confuse the user.
=> fix(start): Comment out panel mockups from the view

src/app/calendar-app/event-editor-dialog.component.ts
=> fix(calendar): Editing an item displays the correct times

src/app/account-app/account-upgrades.component.html, src/app/account-app/account-upgrades.component.ts, src/app/account-app/cart.service.ts, src/app/account-app/shopping-cart.component.html, src/app/account-app/shopping-cart.component.ts
To be merged after the backend limitations are lifted.
=> fix(account): Don't require micro accounts to purchase addons for own domain usage

src/app/calendar-app/calendar-app.component.html, src/app/calendar-app/calendar-app.component.ts, src/app/contacts-app/contacts-app.component.html, src/app/contacts-app/contacts-app.component.ts
=> fix(contacts, calendar): Warn user on incorrect import file types

src/app/canvastable/canvastable.ts, src/app/canvastable/canvastablecontainer.component.html, src/app/common/messagedisplay.ts
=> feat(mailviewer): Add select-all option for selecting messages

e2e/cypress/integration/compose.ts, e2e/cypress/integration/mailviewer.ts, policy-tests/check-commit-log.js, src/app/app.component.ts, src/app/calendar-app/calendar-app.component.ts
Drafting this as it appears to break some tests (and doesn't pass any new ones yet :))
=> fix(webmail): Fix URL navigation

src/app/account-app/shopping-cart.component.html, src/app/account-app/shopping-cart.component.ts, src/app/calendar-app/calendar-app.component.ts
People are ending up with products not available for purchase in their shopping carts, for some reason. A backend fix is in the pipeline to hopefully eliminate these situations, but this should at least enable people to purchase the working things, without locking the cart with products that can't even be removed from it easily.
=> Fix bogus carts

src/app/start/startdesk.component.html, src/app/start/startdesk.component.scss
Mobile view fixed. 
Also commented out the "panel controls" from the view because they had no function yet.
<kbd><img src="https://user-images.githubusercontent.com/24294620/100253227-22504e00-2f41-11eb-839e-caffe741e76d.png"></kbd>
=> style(start): Improve responsivity for mobile screens

src/app/calendar-app/runbox-calendar-event.ts
fixes (or at least improves) #849
=> fix(calendar): Ensure we show recurring events correctly color-tagged

e2e/cypress/integration/mailviewer.ts, src/app/directives/horizresizer.directive.ts, src/app/mailviewer/singlemailviewer.component.ts
Doesnit quiiiite work, @tadzik any ideas? (it's not finding the heightOffsetToPercentage function)
=> fix(mailviewer): Store mail pane height as percentage (not pixels)

src/app/canvastable/canvastable.ts
Previously it'd require you to not do *any* mouse movements between
mousedown and mouseup (while selecting a single row), which would make
it appear inconsistent. This fixes is so that the selection works even
with a slight swipe, as long as the row and column is actually the same
before and after the drag.
Fixes https://github.com/runbox/runbox7/issues/867
=> fix(canvastable): Be a bit more lenient when detecting message selection

src/app/profiles/profiles.editor.modal.html, src/app/profiles/profiles.editor.modal.scss, src/app/profiles/profiles.editor.modal.ts, src/app/profiles/profiles.lister.html, src/app/profiles/profiles.lister.scss, src/app/profiles/profiles.lister.ts
Fixes: #819 
<kbd><img src="https://user-images.githubusercontent.com/24294620/103571232-d04d0180-4eca-11eb-860c-f7a040430d05.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/24294620/103571230-cfb46b00-4eca-11eb-86d2-6a6dc83d008d.png" width="650"></kbd>
=> Make Identities page mobile and desktop friendly

src/app/calendar-app/calendar-app.component.ts
Including new ones added to the end of the list
Fixes: #854
=> fix(calendar): Ensure events are displayed chronologically

src/app/contacts-app/contacts-app.component.ts
Non-vcf file at all, now outputs a more customised message, if passed a broken VCF/VCARD file, will display the parsing error from ical.js
=> fix(contacts): Improve error strictness/messaging on contacts import

src/app/account-app/shopping-cart.component.html
It's currently not working anyway due to changes on bitpay's side.
Hopefully we can replace it with something more reliable soon.
=> feat(payments): disable Bitpay payment option

src/app/account-app/account-addons.component.html, src/app/account-app/account-components.component.html, src/app/account-app/account-renewals.component.html, src/app/account-app/account-transactions.component.html, src/app/account-app/account-upgrades.component.html, src/app/account-app/credit-cards/credit-cards.component.html, src/app/account-security/account.security.component.html, src/app/account-security/account.security.component.scss, src/app/account-security/account.security.component.ts, src/app/profiles/profiles.component.html, src/app/runbox-components/runbox-section.ts, src/styles.scss
<kbd><img src="https://i.imgur.com/lKMXQ5D.png"></kbd>
=> Last logins and sessions mobile fixes

src/app/canvastable/canvastablecontainer.component.html
No idea why I set a z-index initially!
Fixes #909
=> fix(mailview): Don't display select-all checkbox on top of mail pane

src/app/account-app/account-app.module.ts, src/app/account-app/bitpay-payment-dialog.component.html, src/app/account-app/bitpay-payment-dialog.component.ts, src/app/account-app/crypto-payment-description.component.ts, src/app/rmmapi/rbwebmail.ts
Could use some API renames now that it's no longer bitpay-related.
=> fix(payments): Switch cryptocoin payments to a new, non-bitpay API

e2e/cypress/integration/ordering.ts, policy-tests/check-commit-log.js, src/app/account-app/shopping-cart.component.html, src/app/calendar-app/calendar-app.component.ts, src/app/calendar-app/event-editor-dialog.component.ts, src/app/calendar-app/import-dialog.component.ts, src/app/calendar-app/runbox-calendar-event.ts, src/app/calendar-app/runbox-calendar.ts, src/app/changelog/changes.ts
=> Fix build errors

src/app/profiles/profiles.component.html
<kbd><img src="https://i.imgur.com/YnfArZq.png"></kbd>
=> Add helpful text to Identities page

src/app/xapian/searchservice.ts
Here's to hoping this temporary hack doesn't stay there forever :)
=> fix(canvastable): Make inline message previews work again

src/app/app.component.ts, src/app/rmmapi/messagelist.service.ts
=> fix(mailviewer): Sent folder now ignores "unread only" setting

.gitignore, src/app/app.component.ts, src/app/common/messagedisplay.ts
=> fix(mailviewer): Maintain selected messages when new mail appears

src/app/account-security/account.security.component.html, src/app/account-security/account.security.component.scss, src/app/runbox-components/runbox-section.ts, src/styles.scss
=> style(security): Enlarge toggles and improve formatting.

src/app/profiles/profiles.default.ts, src/app/rmm.ts
Fixes compilation errors which somehow got through in CI
=> refactor(app): clear unused imports

e2e/mockserver/emailresponse.ts, src/app/mailviewer/singlemailviewer.component.html, src/app/mailviewer/singlemailviewer.component.ts
=> fix(mailviewer): Load HTML view faster by pre-caching it

src/app/account-app/account-app.component.html, src/app/account-app/account-app.component.scss, src/styles.scss
Before / After
<kbd><img src="https://i.imgur.com/eDJy3MR.png" width="300"></kbd><kbd><img src="https://i.imgur.com/NBzqGKp.png" width="300"></kbd>
=> fix(settings): Fix position of Settings Menu title for mobile

src/app/compose/compose.component.html
Prompt user to download draft attachments, rather than view them.
=> fix(compose): Switch to download prompt for files, to mitigate XSS

src/app/mailviewer/singlemailviewer.component.html
=> fix(mailviewer): Prevent HTML view having multiple scroll layers

src/app/account-app/account-app.component.html, src/app/account-app/account-app.module.ts, src/app/account-app/account-welcome.component.html, src/app/account-security/account-password.component.html, src/app/account-security/account-password.component.ts, src/app/account-security/account.security.component.scss, src/app/account-security/account.security.module.ts
Screenshots:
[Mobile view](https://i.imgur.com/uivXByc.png) / [mobile view with error message](https://i.imgur.com/ROgSyoy.png)
[Desktop view](https://i.imgur.com/nz0MmJ2.png) / [desktop view with error message](https://i.imgur.com/GEc0Vvz.png)  
---
Cases checked before submitting the form:
- If any of the fields are empty
- If new + confirm new passwords match
- If password is 8-64 characters long
- If contains at least 1 alphabetical character
- If contains at least 1 numeric character
- If contains at least 1 special character
The rest is checked by the backend (e.g. if old password is correct).
=> feat(account-security): Add possibility to change Password

src/app/app.component.ts, src/app/canvastable/canvastable.ts
=> fix(mailviewer): Allow message scrolling while pane is open (oops)

src/app/mailviewer/singlemailviewer.component.html, src/app/mailviewer/singlemailviewer.component.ts
=> fix(mailviewer): Remove big icons from print view

src/app/app.component.html, src/styles.scss
<kbd><img src="https://i.imgur.com/7dh05Aq.png"></kbd>
Screenshot taken at 300px width :)
Fixes: #1024
=> fix(app): Fit message list option menu on small mobile screens

src/app/mailviewer/contactcard.component.ts, src/app/mailviewer/singlemailviewer.component.css, src/app/mailviewer/singlemailviewer.component.html
Addresses #1033 
Contact icon scaled down to 0.7 with transform on contactcard, icon resized to fit more with height of text and not overwhelm it and icon changed where relevant.
=> Piratefinn/gh 1033/mailheader improvements

src/app/mailviewer/singlemailviewer.component.ts
Contact and add-contact icons removed!
=> fix(mailviewer): Remove big icons from print view (again)

src/app/account-app/account-renewals.component.html
=> feat(account-app): Remove renewal options from storage space products

src/app/account-app/account-welcome.component.html, src/app/account-app/account-welcome.component.scss
Makes layout more consistent with the Welcome screen while ensuring all titles fit on one line in Firefox, Chrome, and Safari, and that descriptions fill out the boxes nicely.
=> style(settings): Improve text and formatting.

src/app/mailviewer/singlemailviewer.component.ts
Should solve a frequent sentry error
=> fix(mailviewer): Access messageHeaderHTML only when loaded

src/app/mailviewer/singlemailviewer.component.css, src/app/mailviewer/singlemailviewer.component.html, src/app/mailviewer/singlemailviewer.component.ts
Fixing again. Works better than last time. 
HTML messages now have a scrollbar and iFrame doesn't seem to break, so hopefully I nailed it this time.
Fixes #1072
=> fix(mailviewer): Fix horizontal scroll for iframe in message view

src/app/login/login.component.html, src/app/login/login.component.ts
=> style(login): Update payment link and description.

src/app/login/login.component.html, src/app/login/login.component.ts
Included error messages for suspended and expired accounts.
=> fix(login): Improve login error messages and logic.

src/app/login/login.component.html, src/app/login/login.component.ts
The status error messages are now as follows:
**Status 1**
**Status 2**
**Status 3**
**Status 4**
**Status 5**
**Status 6 and up**
=> fix(login): Complete rest of status error messages.

e2e/cypress/integration/ordering.ts, src/app/account-app/account-renewals.component.html, src/app/account-app/shopping-cart.component.html, src/app/account-app/shopping-cart.component.ts
=> Payment special offer sub account

e2e/cypress/integration/payment_methods.ts, src/app/account-app/account-app.component.html, src/app/account-app/account-app.module.ts, src/app/account-app/account-welcome.component.html
=> fix(payment-cards): Change URL for Payment Cards

src/app/mailviewer/singlemailviewer.component.html
=> fix(singlemailviewer): Use TemplateRef instead of Span for ngIfElse

e2e/cypress/integration/compose.ts, src/app/mailviewer/contactcard.component.ts
=> fix(mailviewer): Redirect to Contacts only when clicking the add icon

src/app/app.component.html, src/app/mailviewer/singlemailviewer.component.html
Ref: https://community.runbox.com/t/mark-read-mark-unread/1648
=> style(mail): Replace "mark unread" icon.

src/app/compose/compose.component.scss, src/styles.scss
=> style(compose): Fix width and decrease vertical space.

src/app/contacts-app/contact-list.component.html, src/app/contacts-app/contacts-app.component.html, src/app/contacts-app/contacts-app.component.scss, src/app/contacts-app/contacts-settings.component.html, src/app/contacts-app/contacts-welcome.component.ts, src/styles.scss
=> style(contacts): Improve formatting and wording.

src/app/xapian/searchservice.ts
Needs a backend update, improves our "has attachments" display which
otherwise is only based on "is multipart".
Fixes #521
=> fix(index): Update attachment flag on changes

package-lock.json, package.json, src/app/mailviewer/singlemailviewer.component.ts
Sanitize HTML using a well-known and maintained library
=> refactor(mailviewer): Added DOMPurify for html sanitising

recent-changes.ts, src/app/account-app/account-renewals.component.ts, src/app/account-app/account-transactions.component.ts, src/app/account-app/credit-cards/credit-cards.component.ts, src/app/account-app/paypal-billing-agreements.component.ts, src/app/account-app/runbox-timer.ts, src/app/calendar-app/calendar-app.component.spec.ts, src/app/calendar-app/calendar-overview.component.ts, src/app/calendar-app/calendar.service.spec.ts, src/app/calendar-app/calendar.service.ts, src/app/calendar-app/event-editor-dialog.component.ts, src/app/calendar-app/event-overview.ts, src/app/calendar-app/import-dialog.component.ts, src/app/calendar-app/runbox-calendar-event.spec.ts, src/app/calendar-app/runbox-calendar-event.ts, src/app/changelog/changes.ts, src/app/compose/recipients.service.ts, src/app/contacts-app/contacts.service.ts, src/app/mailviewer/singlemailviewer.component.ts, src/app/rmmapi/rbwebmail.ts, src/app/start/startdesk.component.ts, tsconfig.json
DOMPurify was removing the "target=_blank" - re-added it together with rel="noopener"
=> fix(mailviewer): All email links open in a new tab

src/app/changelog/changelog.component.html, src/app/changelog/changelog.component.scss, src/app/changelog/changelog.component.ts, src/app/login/login.component.html, src/app/updatealert/updatealert.component.html
Add friendly links to the forum from the changelog and update-alert dialog, and a human-readable date format to the changelog.
=> Improve formatting and add links to Runbox 7 forum.

src/app/mailviewer/singlemailviewer.component.ts
More fixes, last tweak didn't turn show images if not previously saved for always/sender
=> fix(mailviewer): Ensure "with images" always turns them off/on

src/app/login/login.component.html, src/app/mailviewer/singlemailviewer.component.html, src/app/mailviewer/singlemailviewer.component.scss, src/app/mailviewer/singlemailviewer.component.ts, src/app/profiles/profiles.component.html, src/styles.scss
=> style(mailviewer): Adjust message display option style and formatting.

src/app/compose/compose.component.ts, src/app/compose/draftdesk.service.ts
Tweak "go back" functionality a bit
=> fix(compose): Ensure we don't lose content of in-progress drafts

src/app/compose/compose.component.ts
=> fix(compose): Ensure drafts refresh keeps compose in-progress

src/app/rmm/email.ts
See also backend changes to fix the actual problem
Fixes #1275
=> fix(maillist): Ensure we display errors when api returns them

src/app/compose/draftdesk.component.ts, src/app/compose/draftdesk.service.ts
Fixes (hopefully) the issue where drafts currently being edited are being closed mid-edit
=> fix(compose): Refreshing drafts should not current edited draft

src/app/account-security/app-passwords.component.ts
=> fix(account-security): Load App Passwords switch enabled, if in use

.github/workflows/ci.yml, package-lock.json, package.json, src/app/account-security/two-factor-authentication.component.html, src/app/rmm/account-security-2fa.ts
Some browsers didn't run the code we were using to generate otpauth
URLs. Replaced the manual code with an library for creating them.
Fixes #1238
=> fix(2fa): QRCodes for 2fa should be readable in more browsers

src/app/profiles/profiles.component.html
Addesses #1091 , a simple text replace which appears to show fine on my local machine.
=> Replaced text for alias as per request from #1091

src/app/calendar-app/event-editor-dialog.component.ts, src/app/calendar-app/runbox-calendar-event.spec.ts, src/app/calendar-app/runbox-calendar-event.ts
=> fix(calendar): Setting "all day" flag on events now saves properly

src/app/rmm/plugin/tinymce.plugin.ts
Needs rethinking (CSP issues)
This reverts commit 87a06f926b81fd976c3af09fd6eedb95c44a4a71.
=> fix(compose): Remove drag&drop to compose html window

src/app/xapian/searchservice.ts
Seems I broke this in the index worker update..
=> fix(inbox): Show notification when new messages appear

src/app/account-app/account-upgrades.component.html
=> style(payment): Add link to Sub-account section.

src/app/account-app/account-transactions.component.ts
=> style(payment): Change description of pending/incomplete transactions.

src/app/app.component.ts, src/app/rmmapi/messagelist.service.ts
=> fix(folders): Ensures we refresh the folder list on a name change

src/app/compose/draftdesk.service.ts, src/app/profiles/profiles.editor.modal.ts, src/app/rmm/profile.ts
Fixes #1378
Also threw out some unused code in rmm profiles
=> fix(drafts): Ensure we only refresh drafts once per folders update

src/app/mailviewer/rmm7messageactions.ts, src/app/rmmapi/messagelist.service.ts
Attempt to fix #1311 where folderCount.total is undefined (somehow!) 
Ensure we show any errors returned from message action operations.
=> fix(delete): Catch/Prevent more errors by ensuring defaults

src/app/mailviewer/singlemailviewer.component.html, src/app/mailviewer/singlemailviewer.component.ts
=> feat(mailviewer): Display incoming attachment sizes

e2e/cypress/integration/compose.ts, e2e/cypress/integration/folder-switching.ts, e2e/cypress/integration/login.ts, e2e/cypress/integration/mailviewer.ts, e2e/cypress/integration/message-caching.ts, src/app/app.component.html, src/app/app.component.ts, src/app/calendar-app/calendar-app.component.spec.ts, src/app/calendar-app/calendar-app.component.ts, src/app/calendar-app/calendar.service.spec.ts, src/app/common/preferences.service.ts, src/app/common/usage-reports.service.ts, src/app/compose/compose.component.html, src/app/compose/compose.component.ts, src/app/contacts-app/contact-details/contact-details.component.html, src/app/contacts-app/contact-details/contact-details.component.ts, src/app/contacts-app/contacts-app.component.html, src/app/contacts-app/contacts-settings.component.html, src/app/contacts-app/contacts-settings.component.ts, src/app/contacts-app/contacts.service.spec.ts, src/app/contacts-app/contacts.service.ts, src/app/mailviewer/avatar-bar.component.ts, src/app/mailviewer/contactcard.component.ts, src/app/mailviewer/singlemailviewer.component.spec.ts, src/app/mailviewer/singlemailviewer.component.ts, src/app/rmmapi/rbwebmail.ts
=> feat(all): Store user preferences on the server

src/app/app.component.html, src/app/app.component.scss
=> style(preview): Improve formatting of the empty preview pane.

src/app/app.component.html, src/app/xapian/multiple-search-fields-input/multiple-search-fields-input.component.html, src/app/xapian/multiple-search-fields-input/multiple-search-fields-input.component.scss, src/app/xapian/multiple-search-fields-input/multiple-search-fields-input.component.ts, src/app/xapian/multiple-search-fields-input/multiple-search-fields-input.module.ts
=> feat(search): Add more options to advanced search pane.

src/app/account-app/stripe-payment-dialog.component.html
See https://github.com/runbox/runbox7/issues/1448
=> fix(payments): Always show "payment not working" for stripe

e2e/cypress/integration/compose.ts, e2e/cypress/integration/mailviewer.ts, e2e/cypress/integration/message-caching.ts, src/app/app.module.ts, src/app/http/progress.service.spec.ts, src/app/rmmapi/messagecache.ts, src/app/rmmapi/rbwebmail.spec.ts, src/app/rmmapi/rbwebmail.ts, src/app/xapian/searchservice.spec.ts
See https://github.com/runbox/private-issues/issues/94
=> fix(messagecache): Change MessageCache to require a user ID

src/app/common/util.spec.ts, src/app/common/util.ts, src/app/compose/compose.component.ts
This should reduce the likelyhood that a draft will be saved after it has been sent.
See https://github.com/runbox/runbox7/issues/644
=> fix(draft): Add distinctUntilChanged for auto save

src/app/app.component.html, src/app/app.component.scss, src/app/canvastable/canvastablecontainer.component.html
=> style(tooltip): Move more tooltips to the left and improve formatting.

src/app/compose/compose.component.ts
See https://github.com/runbox/runbox7/issues/644#issuecomment-1651655948
=> fix(drafts): Drafts are not deleted when the message is sent

src/app/rmm/plugin/tinymce.plugin.ts
=> feat(compose): Add email-safe font selection to HTML/compose editor

src/app/app.component.html, src/app/app.component.ts, src/app/mailviewer/singlemailviewer.component.html, src/app/mailviewer/singlemailviewer.component.ts, src/styles.scss
List message actions:
Message actions with open preview pane:
=> style(menu); Improve display of overflow message action menu items.

src/app/account-app/no-products-for-subaccounts.guard.ts, src/app/http/progress.service.spec.ts, src/app/login/login.component.ts, src/app/rmmapi/rbwebmail.spec.ts, src/app/rmmapi/rbwebmail.ts, src/app/rmmapi/rmmauthguard.service.ts, src/app/xapian/searchservice.spec.ts
=> fix(login): Redirect to subscriptions after login if began there

src/app/account-app/no-products-for-subaccounts.guard.ts, src/app/rmmapi/rmmauthguard.service.ts
Layers of "canActivate" could fetch the "me" API endpoint 4 times in one page load, have consolidated this into one fetch per load/activate check.
=> fix(account): Refetch / check userinfo less when activating pages

e2e/cypress/integration/ordering.ts, e2e/mockserver/mockserver.ts, src/app/account-app/account-product.component.html, src/app/account-app/account-product.component.ts, src/app/account-app/account-renewals.component.html, src/app/account-app/account-renewals.component.ts, src/app/account-app/account-upgrades.component.html, src/app/account-app/account-upgrades.component.ts, src/app/account-app/product.ts, src/app/account-details/storage-data.component.html, src/app/account-details/storage-data.component.ts, src/app/rmm/account-storage.ts, src/app/rmm/alias.ts
=> feature(products): Product pages show usage hints

e2e/cypress/integration/ordering.ts, src/app/account-app/account-app.component.scss, src/app/account-app/account-product.component.html, src/app/account-app/account-product.component.scss, src/app/account-app/account-product.component.ts, src/app/account-app/account-upgrades.component.html, src/app/account-app/account-upgrades.component.scss, src/app/account-app/account-upgrades.component.ts, src/app/app.component.html, src/app/calendar-app/calendar-app.component.html, src/app/contacts-app/contacts-app.component.html, src/app/onscreen/onscreen.component.html, src/app/runbox-components/runbox-container.html, src/app/start/overview.component.html, src/styles.scss
=> style(payment): Improve text, formatting, and usage hints.

src/app/account-app/account-renewals.component.html, src/app/account-app/account-renewals.component.ts
=> fix(subscriptions): Cope with "no active subscriptions" with link

src/app/rmmapi/rmmauthguard.service.ts
=> fix(login): Stay on login screen if cache deleted / cookies expired

src/app/compose/draftdesk.component.ts
=> fix(compose): Current draft, newest drafts, are now at the top

src/app/app.component.ts
Fixes issue reported by support
=> fix(messagelist): Ensures Threaded, Unread not set together

src/app/xapian/index.worker.ts, src/app/xapian/searchservice.ts
Mostly, if there's an error from the worker thread, and localSearch is turned off, assume its a deleteindex fail, close the progress dialog, and refresh the message list via the api.
=> fix(index): Recover from index removal stalling

src/app/mailviewer/singlemailviewer.component.ts, src/app/rmmapi/messagelist.service.ts, src/app/rmmapi/restapi_standalone.ts, src/app/updatealert/updatealert.service.ts, src/app/xapian/index.worker.ts
Various tweaks that should clear up some constantly reported errors in Sentry
=> Sentry fixups

src/app/xapian/searchservice.ts
This reverts commit 05f0d1bde40c2917df40da546f15642042315a84.
=> Revert "feat(index): Creates a browser-local index if not downloadable"

src/app/rmmapi/rbwebmail.ts
See https://github.com/runbox/runbox7/issues/1555
=> fix(messages): Use batch_delete for deleting multiple messages

e2e/cypress/integration/ordering.ts, e2e/mockserver/mockserver.ts, src/app/account-app/account-product.component.html, src/app/account-app/account-product.component.scss, src/app/account-app/account-upgrades.component.html, src/app/account-app/account-upgrades.component.scss, src/app/account-app/account-upgrades.component.ts, src/styles.scss
style(payment): Add recommended plans and make table more dynamic.
=> style(payment): Add recommended plans and make table more dynamic.

angular.json
Set the angular analytics to be disabled using the angular config.
=> fix(config): Opt-out of angular analytics

src/app/account-app/account-app.component.html, src/app/account-details/account-details.component.scss, src/app/account-details/personal-details.component.html, src/app/account-details/personal-details.component.ts, src/app/app.component.html, src/app/rmm/account-details.ts, src/app/welcome/welcomedesk.component.html, src/app/welcome/welcomedesk.component.spec.ts, src/app/welcome/welcomedesk.component.ts
If alt email is changed, resend validation email
Fixes #1510
=> feat(account): Allows resending of alt email validation

src/app/app.component.html
Invert meaning, instead of display when validated!
=> fix(sidebar): Display Alt validation warning if unvalidated

src/app/app.component.ts, src/app/rmmapi/messagelist.service.spec.ts, src/app/rmmapi/messagelist.service.ts, src/app/xapian/index.worker.ts
Not indexed as it does not contain complete email messages.
Also: fix #1222
=> fix(messagelist): Show Templates folder contents from API

package-lock.json, package.json
Reverting to runbox-searchindex 0.2.3 as that seems to work better
=> build(xapian): Fixes bug with delayed markSeen on message-open

src/app/app.component.ts
=> fix(messagelist): Clear message selection after user action

src/app/app.component.html, src/app/app.component.ts, src/app/canvastable/canvastable.ts, src/app/mailviewer/singlemailviewer.component.ts
=> fix(messagelist): Ensure opened message row is visible in list

src/app/account-app/account-upgrades.component.html
=> style(payment): Make currency formats consistent.

e2e/cypress/integration/compose.ts, src/app/rmmapi/rbwebmail.ts, src/app/rmmapi/restapi_standalone.ts, src/app/xapian/searchservice.spec.ts
=> fix(index): More service worker skipping for index downloads

src/app/account-app/stripe-payment-dialog.component.ts
Test cards to force 3ds flow if needed: https://docs.stripe.com/payments/3d-secure/authentication-flow?platform=react-native#three-ds-cards
HandleNextAction doc: https://docs.stripe.com/payments/finalize-payments-on-the-server?platform=web&type=payment#next-actions
=> fix(payments): Accept 3DSecure payments correctly

src/app/app.component.ts, src/app/mailviewer/rmm7messageactions.ts
After the spam/ham "learn" report, output the results in a self-closing snackbar
=> fix(spam): Report results of spam/ham training

src/app/login/login.component.html, src/app/login/login.component.ts
On browser start the inputs are pre-filled. When pressing login it does not work. The form value is not correct resulting in this body:
=> Login filled out but request has empty user

package-lock.json, package.json, src/polyfills.ts
This wasn't ready yet
This reverts commit 5c54287c2a4f4023799294da3bbfcd240d9c9fc3, reversing changes made to 32759b7df8ac28c11d45459c866820d5ce74ea6e.
=> fix(build): Remove unused dependencies (revert)

src/app/account-app/account-renewals.component.ts
=> fix(subscriptions): Only warn about close-quota for Disk/File quotas

package-lock.json, package.json, src/app/sentry.ts
The downgrade did the job and uses the `/store` with a 200 status.
=> fix(sentry): Downgrade client to make it work with sentry server
